<?php
// HABILITAR VISUALIZACIÓN DE ERRORES PHP (solo en desarrollo)
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Iniciar sesión si no está iniciada
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Add error popup handling after session_start()
if (isset($_SESSION['msg_error'])) {
    echo "<script>
        window.addEventListener('DOMContentLoaded', function() {
            alert('" . addslashes($_SESSION['msg_error']) . "');
        });
    </script>";
    unset($_SESSION['msg_error']); // Clear the message after displaying
}

$_ERRORS = array();

if (!function_exists("my_error_handler")) {
    function my_error_handler($code, $message, $file, $line)
    {

        global $_ERRORS;


        $_ERRORS[] = sprintf('"%s" (%s line %s)', $message, $file, $line);

    }
}

set_error_handler('my_error_handler', E_ALL & ~E_NOTICE);


if (!function_exists("fatal_handler")) {
    function fatal_handler()
    {

        global $_ERRORS;

        $errfile = "unknown file";
        $errstr = "shutdown";
        $errno = E_CORE_ERROR;
        $errline = 0;
        $archivos_incluidos = get_included_files();
        $error = error_get_last();


        if ($error !== NULL) {

            $errno = $error["type"];
            $errfile = $error["file"];
            $errline = $error["line"];
            $errstr = $error["message"];

            // Initialize message string
            $manda = "CODIGOAMIGO*\n";

            foreach ($_ERRORS as $a => $line) {
                $manda .= "***" . $line . "*****\n";
            }

            if ($errno == 1 || $errno == 4) { //SOLO FATALES

                $manda .= $errno . "\n" . $errfile . "\n" . $errline . "\n" . $errstr;



                if ($archivos_incluidos) {
                    $limit = 0;
                    $last_file = "";
                    foreach ($archivos_incluidos as $nombre_archivo) {
                        if ($limit <= 5) {
                            $last_file .= "\n::" . $nombre_archivo;
                        }
                        $limit++;
                    }
                    $manda .= "\n\nEncontrado en: " . $last_file . "...";
                }

                $botToken = "1208948207:AAF0O45V1zcsp7wjRgbwOrLQ7tNRUHlfnME";
                //$chatId="-1001249170942";
                $chatId = "-563343505";

                $url = "https://api.telegram.org/bot" . $botToken . "/sendMessage?chat_id=" . $chatId;

                $post = [
                    'chat_id' => $chatId,
                    'text' => $manda
                ];

                $curl = curl_init();
                curl_setopt($curl, CURLOPT_URL, $url);
                curl_setopt($curl, CURLOPT_POSTFIELDS, $post);
                curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

                $data = curl_exec($curl);

                curl_close($curl);

                //decoding request
                $result = json_decode($data, true);
            }
        }
    }
}



register_shutdown_function("fatal_handler");



// autoload.php @generated by Composer

//NO CACHEO VARNISH SI ESTA LOGUEADO
if ($_SESSION['user_id']) {
    header("Cache-Control: no-cache, must-revalidate");
    header("Expires: $ts");
    header("Last-Modified: $ts");
    header("Pragma: no-cache");
    session_cache_limiter('');
}




// Configuración de sesiones - Sesión infinita (10 años)
$lifetime = 315360000; // 10 años en segundos (60*60*24*365*10)
ini_set('session.gc_maxlifetime', $lifetime); // Tiempo de vida de los archivos de sesión en el servidor
ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_secure', isset($_SERVER['HTTPS']) ? 1 : 0);
ini_set('session.use_strict_mode', 1);
ini_set('session.cookie_samesite', 'Lax');
// Configurar cookie de sesión con lifetime muy alto
session_set_cookie_params($lifetime, '/', ".codigoamigo.com");


if ((strstr($_SERVER['HTTP_USER_AGENT'], 'casinuevo_debug'))) {
    $admin_user = 1;
    $debugAdmin = 1;
    $GLOBALS["debugAdmin"] = 1;
}

if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'http' || !$_SERVER['HTTP_X_FORWARDED_PROTO']) {

    $http = "http://";

} elseif ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {

    $http = "https://";

}

$http = "https://";

if (strstr($_SERVER['SERVER_NAME'], "dev.")) {
    $GLOBALS["website"] = "https://dev.codigoamigo.com/";
} else {
    $GLOBALS["website"] = "https://www.codigoamigo.com/";
}




$GLOBALS["actual_url"] = $http . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
$GLOBALS["actual_url_limpia"] = strtok($GLOBALS["actual_url"], '?');
$GLOBALS["site_twitter"] = "@codigoamigocom";
$GLOBALS["site_facebook"] = "";
$GLOBALS["author"] = "CODIGOAMIGO.COM";
$GLOBALS["image_src"] = "";
$GLOBALS["pagina"] = "";
$GLOBALS["image_new_marca"] = "";

$show_adsense = 1;
$show_addthis = 1;

// Configuración de error reporting
error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', '/home/admin/web/codigoamigo.com/public_html/php_errors.log');

// Modo debug activable por URL: ?debug=1
$DEBUG_MODE = false; // Deshabilitado para logear errores en archivos
if ($DEBUG_MODE) {
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
}

// Mejorar la función de debug
function debug_log($message, $data = null)
{
    $log = date('Y-m-d H:i:s') . " - " . $message;
    if ($data !== null) {
        $log .= "\nData: " . print_r($data, true);
    }
    if ($data instanceof Exception) {
        $log .= "\nStack trace: " . $data->getTraceAsString();
    }
    error_log($log . "\n", 3, __DIR__ . '/debug.log');
}

// Agregar manejador de errores fatal mejorado
set_exception_handler(function ($e) {
    // Solo logear errores críticos, no warnings o notices
    if ($e instanceof Error || $e instanceof Exception) {
        debug_log('Fatal Error:', $e);
        
        // En producción, no mostrar detalles salvo si DEBUG_MODE está activo
        if (defined('ENVIRONMENT') && ENVIRONMENT === 'production' && empty($GLOBALS['DEBUG_MODE']) && empty($DEBUG_MODE)) {
            http_response_code(500);
            echo json_encode([
                'error' => 'Internal Server Error',
                'message' => 'An error occurred. Please try again later.'
            ]);
        } else {
            http_response_code(500);
            if (!empty($DEBUG_MODE)) {
                header('Content-Type: text/plain; charset=utf-8');
                echo "Fatal Exception\n";
                echo "Message: " . $e->getMessage() . "\n";
                echo "File: " . $e->getFile() . "\n";
                echo "Line: " . $e->getLine() . "\n\n";
                echo $e->getTraceAsString();
            } else {
                echo json_encode([
                    'error' => 'Internal Server Error',
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine()
                ]);
            }
        }
    }
});

/********************************************************************
 * SLIM
 *******************************************************************/


require __DIR__ . '/vendor/autoload.php';
use Spatie\ImageOptimizer\OptimizerChainFactory;



$app = new \Slim\App([
    'settings' => [
        'displayErrorDetails' => ($DEBUG_MODE ? true : false),
        'addContentLengthHeader' => false,
        'debug' => ($DEBUG_MODE ? true : false),
        'determineRouteBeforeAppMiddleware' => true
    ]
]);

$actual_url = "https://" . $_SERVER["HTTP_HOST"] . (rawurldecode($_SERVER["REQUEST_URI"]));

$actual_url_limpia_arr = explode("?", $actual_url);

$actual_url_limpia = $actual_url_limpia_arr[0];


if (filter_input(INPUT_GET, "continua_viendo", FILTER_SANITIZE_FULL_SPECIAL_CHARS) == 1) {

    header("location:" . $actual_url_limpia, TRUE, 301);

}


include_once __DIR__ . '/inc/includes.php';
include_once __DIR__ . '/myphp/funciones.php';
include_once __DIR__ . '/myphp/_header.php';

// Handlers de error para logging a error_log (Slim 3)
$container = $app->getContainer();
$container['errorHandler'] = function($c) {
    return function($request, $response, $exception) use ($c) {
        error_log('[EXCEPTION] '.get_class($exception).': '.$exception->getMessage().' in '.$exception->getFile().':'.$exception->getLine()."\n".$exception->getTraceAsString());
        return $c['response']->withStatus(500)->write('Internal Server Error');
    };
};
$container['phpErrorHandler'] = function($c) use ($container) {
    return $container['errorHandler'];
};
$container['notFoundHandler'] = function($c) {
    return function($request, $response) use ($c) {
        error_log('[404] '.$request->getUri());
        return $c['response']->withStatus(404)->write('Not Found');
    };
};


$app->post('/ajax', function ($request, $respon) {
    votar_codigo($_POST);
});

// Ruta AJAX para el rediseño
$app->any('/ajax/redesign', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/ajax/redesign_ajax.php';
});

// Ruta para el listado rediseñado
$app->get('/listado', function ($request, $respon) {
    // Incluir configuración del rediseño
    // require_once __DIR__ . '/redesign_config.php'; // Archivo no existe en backup original
    
    // if (is_redesign_enabled()) { // Función no disponible sin redesign_config.php
    //     include_once $_SERVER['DOCUMENT_ROOT'] . '/public/listado_real.php';
    //     return $respon;
    // }
    
    // Código original para listado si el rediseño no está habilitado
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/listado_categorias.php';
});

// Ruta para URLs de Afiliados
$app->get('/afiliados', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/afiliados.php';
});

// Ruta para Panel de Administración de Afiliados
$app->get('/admin_afiliados', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/admin_afiliados.php';
});

// Ruta para Ingresos de Afiliado específico
$app->get('/ingresos_afiliado', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/ingresos_afiliado.php';
});

// Ruta para fichas rediseñadas
$app->get('/ficha/{id}', function ($request, $respon, $args) {
    // Incluir configuración del rediseño
    // require_once __DIR__ . '/redesign_config.php'; // Archivo no existe en backup original
    
    // if (is_redesign_enabled()) { // Función no disponible sin redesign_config.php
    //     include_once $_SERVER['DOCUMENT_ROOT'] . '/public/ficha_redesign.php';
    //     return $respon;
    // }
    
    // Código original para fichas si el rediseño no está habilitado
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/marca.php';
});

// Ruta para búsqueda rediseñada (integrada en la ruta existente)



/********************************************************************
 * MOBILE OR PC
 *******************************************************************/



/********************************************************************
 * 301
 *******************************************************************/
$url_move_fix = str_replace("http://", "https://", $GLOBALS["actual_url"]);


if ($GLOBALS["actual_url"] != $url_move_fix) {
    header("Location: " . $url_move_fix);
}

/********************************************************************
 * PANEL DE CONTROL
 *******************************************************************/

// Include Mobile_Detect library
include_once __DIR__ . '/../myphp/librerias/Mobile_Detect.php';

$detect = new Mobile_Detect();
global $detect;
$GLOBALS["detect"] = $detect;

$app->get('/panel-de-control-codigos', function ($request, $respon) {
    global $panel;

    $panel = 1;

    $title = "Panel de control de códigos";
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_codigos.php';

});

$app->get('/panel-de-control-marcas', function ($request, $respon) {

    global $panel;

    $panel = 1;

    $title = "Panel de control marcas";
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_marcas.php';

});



$app->get('/panel-de-control-marcas-edita-marcas', function ($request, $respon) {

    global $panel, $marca;

    $panel = 1;

    $title = "Panel de control marcas";




    $marca = getObjectMarca('_id', new \MongoDB\BSON\ObjectId($_REQUEST['id_marca']));



    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_marcas_edita_marca.php';

});

$app->post('/panel-de-control-marcas-edita-marcas', function ($request, $respon) {

    global $panel, $marca;

    $panel = 1;

    $title = "Panel de control marcas";

    $marca = getObjectMarca('_id', new \MongoDB\BSON\ObjectId($_REQUEST['id_marca']));

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_marcas_edita_marca.php';

});

$app->get('/panel-de-control-marcas-edita-foto', function ($request, $respon) {

    global $panel;

    $panel = 1;

    $title = "Panel de control marcas";
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_marcas_edita_foto.php';

});

$app->get('/panel-de-control-usuarios', function ($request, $respon) {

    global $panel;

    $panel = 1;

    $title = "Panel de control usuarios";

});

/********************************************************************
 * NUEVO PANEL DE ADMINISTRACIÓN COMPLETO
 *******************************************************************/

$app->get('/admin', function ($request, $respon) {
    header('Location: /public/admin_dashboard.php');
    exit;
});

$app->get('/admin_dashboard', function ($request, $respon) {
    header('Location: /public/admin_dashboard.php');
    exit;
});

$app->get('/admin_usuarios', function ($request, $respon) {
    header('Location: /public/admin_usuarios.php');
    exit;
});

$app->get('/admin_marcas', function ($request, $respon) {
    header('Location: /public/admin_marcas.php');
    exit;
});

$app->get('/admin_codigos', function ($request, $respon) {
    header('Location: /public/admin_codigos.php');
    exit;
});

$app->get('/admin_transacciones', function ($request, $respon) {
    header('Location: /public/admin_transacciones.php');
    exit;
});

$app->get('/admin_reportes', function ($request, $respon) {
    header('Location: /public/admin_reportes.php');
    exit;
});

$app->get('/admin_configuracion', function ($request, $respon) {
    header('Location: /public/admin_configuracion.php');
    exit;
});

$app->get('/admin_logs', function ($request, $respon) {
    header('Location: /public/admin_logs.php');
    exit;
});

$app->get('/admin_chat', function ($request, $respon) {
    header('Location: /public/admin_chat.php', true, 302);
    exit;
});

$app->get('/admin_chollos', function ($request, $respon) {
    header('Location: /public/admin_chollos.php');
    exit;
});

$app->get('/admin_newsletters', function ($request, $respon) {
    header('Location: /public/admin_newsletters.php');
    exit;
});

/********************************************************************
 * CHOLLOS
 *******************************************************************/

// Incluir funciones de chollos
include_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/funciones_chollos.php';
include_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/funciones_chollos_amazon.php';
include_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/funciones_chollos_groq.php';

// Ruta principal de chollos
$app->get('/chollos', function ($request, $respon) {
    global $panel, $detect;
    
    // Inicializar variables globales
    $GLOBALS['website'] = 'https://www.codigoamigo.com/';
    $GLOBALS['actual_url'] = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
    
    // Incluir archivos necesarios
    include_once __DIR__ . '/inc/includes.php';
    include_once __DIR__ . '/myphp/funciones.php';
    
    // Inicializar detector de móviles
    if (!isset($detect)) {
        $detect = new Mobile_Detect();
    }
    $GLOBALS['detect'] = $detect;
    
    // Incluir funciones modernas
    include_once __DIR__ . '/myphp/funciones_modern.php';
    include_once __DIR__ . '/myphp/_header_modern.php';
    $GLOBALS['header_modern_used'] = true;
    
    // Obtener chollos
    $filtros = [
        'estado' => 1,
        'limite' => 24
    ];
    
    if (isset($_GET['categoria']) && !empty($_GET['categoria'])) {
        $filtros['categoria'] = $_GET['categoria'];
    }
    
    if (isset($_GET['busqueda']) && !empty($_GET['busqueda'])) {
        $filtros['busqueda'] = $_GET['busqueda'];
    }
    
    $chollos = obtenerChollos($filtros);
    $categorias = obtenerCategoriasChollos();
    
    // Llamar a la función del header moderno
    get_header_modern(
        "Chollos y Ofertas - CodigoAmigo.com",
        "Descubre los mejores chollos y ofertas de Amazon, Black Friday, electrónica, moda y más. Ahorra dinero con nuestras ofertas exclusivas.",
        "chollos, ofertas, descuentos, amazon, black friday, electrónica, moda"
    );
    
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/chollos_listado.php';
    
    return $respon;
});

// Ruta del acortador de chollos /chollo/{id} - DEBE IR ANTES DE RUTAS GENÉRICAS
$app->get('/chollo/{id}', function ($request, $respon, $args) {
    // Incluir archivos necesarios
    include_once __DIR__ . '/inc/includes.php';
    include_once __DIR__ . '/myphp/funciones.php';
    include_once __DIR__ . '/myphp/funciones_chollos.php';
    
    $chollo_id = $args['id'] ?? '';
    
    // Log para debugging
    error_log("Acortador chollo - ID recibido: " . $chollo_id);
    
    if (empty($chollo_id)) {
        error_log("Acortador chollo - ID vacío, redirigiendo a /chollos");
        return $respon->withRedirect('/chollos', 301);
    }
    
    // Obtener el chollo sin incrementar clicks (usaremos registrarClickChollo después)
    $collection = getCollectionChollos();
    if (!$collection) {
        error_log("Acortador chollo - Error: No se pudo obtener colección");
        return $respon->withRedirect('/chollos', 301);
    }
    
    try {
        $objectId = new MongoDB\BSON\ObjectId($chollo_id);
        $doc = $collection->findOne(['_id' => $objectId]);
        
        if (!$doc) {
            error_log("Acortador chollo - Chollo no encontrado con ID: " . $chollo_id);
            return $respon->withRedirect('/chollos', 301);
        }
        
        if (empty($doc['enlace'])) {
            error_log("Acortador chollo - Chollo sin enlace, ID: " . $chollo_id);
            return $respon->withRedirect('/chollos', 301);
        }
        
        $enlace = $doc['enlace'];
        error_log("Acortador chollo - Enlace encontrado: " . $enlace);
        
        // Redirigir a la URL original del chollo (absoluta)
        if (!preg_match('/^https?:\/\//', $enlace)) {
            // Si no tiene protocolo, añadir https://
            $enlace = 'https://' . $enlace;
        }

        // Preparar datos para tracking
        $enlace_original = $enlace;
        $es_amazon = esEnlaceAmazon($enlace);
        
        // Cargar funciones de Amazon si no están cargadas
        include_once __DIR__ . '/myphp/funciones_chollos_amazon.php';
        
        $asin = null;
        if ($es_amazon) {
            error_log("Acortador chollo - Es enlace de Amazon, aplicando tagging...");
            $enlace = convertirEnlaceAmazonGarantizado($enlace, $chollo_id);
            $asin = extraerASIN($enlace);
        }

        // Registrar el click con información detallada
        $datos_click = [
            'enlace_original' => $enlace_original,
            'enlace_final' => $enlace,
            'es_amazon' => $es_amazon,
            'tiene_tag_afiliado' => ($es_amazon && strpos($enlace, 'tag=spnfuryy-21') !== false)
        ];
        if ($asin) { $datos_click['asin'] = $asin; }

        registrarClickChollo($chollo_id, $datos_click);
        
        error_log("Acortador chollo - Redirigiendo a: " . $enlace);
        return $respon->withRedirect($enlace, 302);
    } catch (Exception $e) {
        error_log("Error en acortador de chollo: " . $e->getMessage() . " - ID: " . $chollo_id);
        error_log("Stack trace: " . $e->getTraceAsString());
        return $respon->withRedirect('/chollos', 301);
    }
});

// Ruta de detalle individual - Redirige directamente al short link
$app->get('/chollos/{categoria}/{id}', function ($request, $respon, $args) {
    $id = $args['id'];
    
    // Redirigir directamente al short link que lleva a Amazon
    return $respon->withRedirect('/chollo/' . $id, 301);
});

// Webhook para Telegram
$app->post('/webhook/telegram-chollos', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/telegram_chollos_bot.php';
    procesarMensajeTelegram($request->getBody());
    return $respon->withJson(['success' => true]);
});

$app->get('/panel-de-control-usuarios', function ($request, $respon) {

    global $panel;

    $panel = 1;

    $title = "Panel de control usuarios";

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/_panel_de_control_usuarios.php';

});

/********************************************************************
 * HOME
 *******************************************************************/

/********************************************************************
 * USUARIO
 *******************************************************************/

global $data_usuario;


if (!$_SESSION['user_id'] || $_SESSION['user_id'] == "") {

    $data_usuario = "";

} else {

    $object_mongodb = new \MongoDB\BSON\ObjectId($_SESSION['user_id']);
    $usuario = getObjectUser('_id', $object_mongodb);
    $data_usuario = get_array_de_usuario($usuario);

}




$app->get('/test2', function ($request, $respon) {
    // Incluir el helper de email
    require_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/email_helper.php';
    
    // Usar la función helper con fallback automático
    $result = enviarEmailContacto($datos, $url_logo_web);
    
    echo "<pre>";
    echo "Email sending result:\n";
    echo "Success: " . ($result['success'] ? 'Yes' : 'No') . "\n";
    echo "Method: " . $result['method'] . "\n";
    echo "</pre>";
    
    if (!$result['success']) {
        mandaBot("Email sending failed using both SendGrid and PHP mail()");
    }

});

$app->get('/ofertas/{termino}', function ($request, $respon, $args) {
    global $author_web, $name_page;

    $termino = $args['termino'];

    // Sanitizar el término de búsqueda
    $termino = htmlspecialchars(trim($termino), ENT_QUOTES, 'UTF-8');

    // Incluir funciones de búsqueda mejorada
    include_once $_SERVER['DOCUMENT_ROOT'] . '/myphp/funciones_busqueda.php';

    // Procesar el término de búsqueda para manejar espacios y múltiples palabras
    $terminos_busqueda = procesar_termino_busqueda($termino);

    // Buscar en marcas con filtro mejorado
    $array_filtro_marcas = crear_filtro_marcas_mejorado($terminos_busqueda);
    $lista_marcas = buscar_marcas_mejorado($array_filtro_marcas);

    // Buscar en códigos con términos mejorados
    $array_filtro_codigos = crear_filtro_codigos_mejorado($terminos_busqueda);

    // Primero obtener códigos DESTACADOS que coincidan con la búsqueda
    // Combinar el filtro de búsqueda con el filtro de destacados usando $and
    $array_filtro_destacados = array();
    
    // Copiar todos los filtros excepto $or
    foreach ($array_filtro_codigos as $key => $value) {
        if ($key !== '$or') {
            $array_filtro_destacados[$key] = $value;
        }
    }
    
    // Combinar condiciones de búsqueda y destacados con $and
    $and_conditions = array();
    
    // Añadir condición de búsqueda si existe
    if (isset($array_filtro_codigos['$or'])) {
        $and_conditions[] = array('$or' => $array_filtro_codigos['$or']);
    }
    
    // Añadir condición de destacados (destacado o destacado_social)
    $and_conditions[] = array(
        '$or' => array(
            array('destacado' => array('$ne' => 0)),
            array('destacado_social' => array('$ne' => 0))
        )
    );
    
    if (!empty($and_conditions)) {
        $array_filtro_destacados['$and'] = $and_conditions;
    }
    
    $array_opciones_destacados = array(
        'limit' => 50,  // Aumentar límite para obtener más destacados
        'sort' => array('destacado_social' => -1, 'destacado' => -1, '_id' => -1)
    );
    
    $lista_codigos_destacados = get_all_listado_codigos_array($array_filtro_destacados, $array_opciones_destacados);
    $codigos_destacados = isset($lista_codigos_destacados["results"]) ? $lista_codigos_destacados["results"] : [];
    
    // Luego obtener códigos NO DESTACADOS que coincidan con la búsqueda
    // Excluir tanto destacado como destacado_social
    $array_filtro_normales = array();
    
    // Copiar todos los filtros excepto $or
    foreach ($array_filtro_codigos as $key => $value) {
        if ($key !== '$or') {
            $array_filtro_normales[$key] = $value;
        }
    }
    
    // Añadir condición de búsqueda si existe
    if (isset($array_filtro_codigos['$or'])) {
        $array_filtro_normales['$or'] = $array_filtro_codigos['$or'];
    }
    
    // Excluir destacados: destacado = 0 Y destacado_social = 0 (o no existe)
    $array_filtro_normales['$and'] = array(
        array('destacado' => 0),
        array('$or' => array(
            array('destacado_social' => array('$exists' => false)),
            array('destacado_social' => 0)
        ))
    );
    
    $array_opciones_normales = array(
        'limit' => 50,  // Aumentar límite
        'sort' => array('_id' => -1)
    );
    
    $lista_codigos_normales = get_all_listado_codigos_array($array_filtro_normales, $array_opciones_normales);
    $codigos_normales = isset($lista_codigos_normales["results"]) ? $lista_codigos_normales["results"] : [];
    
    // Combinar: primero destacados, luego normales
    $lista_codigos_combinada = array_merge($codigos_destacados, $codigos_normales);
    
    // Recrear la estructura esperada con los resultados combinados
    $lista_codigos = array(
        'results' => $lista_codigos_combinada,
        'total_number' => count($lista_codigos_combinada)
    );

    // Configurar variables para la vista
    $title = htmlspecialchars($termino) . " ofertas y chollos";
    $description = htmlspecialchars($termino) . " ofertas y chollos. Encuentra las mejores ofertas, códigos descuento y cupones para " . htmlspecialchars($termino) . " en " . $author_web;
    $name_page = "busqueda";


    // Registrar búsqueda (no bloqueante) - solo si no viene de tendencias
    $from_trends = filter_input(INPUT_GET, "from", FILTER_SANITIZE_FULL_SPECIAL_CHARS) === 'trends';
    if (!$from_trends) {
        try { 
            if (function_exists('record_search_term')) {
                record_search_term($termino); 
            }
        } catch (Throwable $e) { 
            // Log del error pero no bloquear la búsqueda
            error_log("Error registrando búsqueda: " . $e->getMessage());
        }
    }

    // Incluir la vista
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/busqueda.php';
});


$app->get('/', function ($request, $respon) {
    global $author_web, $detect, $num_inicio, $name_page, $num_fin, $codigos_restantes, $lista_codigos, $skip_patrocinados, $num_destacados, $num_codes;
    
    // Asegurar que $detect esté inicializado
    if (!isset($detect)) {
        $detect = new Mobile_Detect();
    }
    
    // Inicializar variables por defecto
    $num_inicio = 1;
    $num_fin = 20;
    $codigos_restantes = 0;
    $lista_codigos = array();
    $skip_patrocinados = 0;
    $num_destacados = 0;
    $num_codes = 0;

    /************************************************
     * Códigos a mostrar
     ************************************************/

    $newURL = strtok($GLOBALS["actual_url"], '?');

    if ($_REQUEST["page"]) {
        $limit = 97;
        $limit2 = 100;
    } else {
        $limit = 50; // Aumentar límite para códigos destacados
        $limit2 = 9; // Limitar a 9 códigos en la home para dar espacio
    }



    /* Para saber cuantos codigos tengo que saltar segun la página donde estoy */
    $skip = get_skip_in_pagination();
    $skip_patrocinados = get_skip_patrocinados_in_pagination();


    // Determinar el orden según el parámetro recibido
    $sort_order = array('fecha_publicacion' => -1); // orden por defecto: más recientes primero por fecha

    $orden_param = filter_input(INPUT_GET, 'orden', FILTER_SANITIZE_FULL_SPECIAL_CHARS);
    if ($orden_param !== null) {
        switch ($orden_param) {
            case 'beneficio':
                $sort_order = array('num_beneficio' => -1);
                break;
            case 'valoraciones':
                $sort_order = array('num_valoraciones' => -1);
                break;
            case 'antiguos':
                $sort_order = array('fecha_publicacion' => 1);
                break;
            case 'recientes':
                $sort_order = array('fecha_publicacion' => -1);
                break;
        }
    }

    $sort_order_destacados = array('destacado_social' => -1, '_id' => -1);


    /* Listado DESTACADOS */
    $array_filtro = array("estado" => array('$in' => [0, -1, 1]));
    $array_filtro = array_merge($array_filtro, array("destacado_social" => array('$ne' => 0)));

    $array_skip = array("limit" => $limit);
    $array_skip = array_merge($array_skip, array("skip" => $skip_patrocinados));
    $array_skip = array_merge($array_skip, array("sort" => $sort_order_destacados)); // Aplicar orden


    //TOMO LOS CODIGOS
    $lista_codigos_patrocinados_pre = get_all_listado_codigos_array($array_filtro, $array_skip);
    $lista_codigos_patrocinados = $lista_codigos_patrocinados_pre["results"];

    /* Listado NORMAL */
    $array_filtro = array("estado" => array('$in' => [0, -1, 1]));
    $array_filtro = array_merge($array_filtro, array("destacado" => 0));

    $array_skip = array("limit" => $limit2);
    $array_skip = array_merge($array_skip, array("skip" => $skip));
    $array_skip = array_merge($array_skip, array("sort" => $sort_order));

    //TOMO LOS CODIGOS
    $lista_codigos_pre = get_all_listado_codigos_array($array_filtro, $array_skip);

    $lista_codigos = isset($lista_codigos_pre["results"]) && is_array($lista_codigos_pre["results"]) ? $lista_codigos_pre["results"] : [];
    $numero_codigos = isset($lista_codigos_pre["total_number"]) ? $lista_codigos_pre["total_number"] : 0;

    /* MERGE - Mostrar todos los destacados, no solo 3 */
    $lista_codigos = array_merge(
        (is_array($lista_codigos_patrocinados) && !empty($lista_codigos_patrocinados) ? $lista_codigos_patrocinados : []),
        (is_array($lista_codigos) && !empty($lista_codigos) ? $lista_codigos : [])
    );
    
    // Limitar a 9 códigos totales en la home (sin página) para dar espacio
    if (!$_REQUEST["page"]) {
        $lista_codigos = array_slice($lista_codigos, 0, 9);
    }
    $total_pag = (intval($numero_codigos / 10)) + 1;

    if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 999 || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > $total_pag || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) == 1) {
        return $respon->withRedirect($newURL, 301);
    }

    if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) == "") {
        $codigos_restantes = $numero_codigos;
        $num_inicio = 1;
        $num_fin = 20;
    } else {
        $num_inicio = (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10) - 9;
        $num_fin = filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10;
        if ($num_fin > $numero_codigos) {
            $num_fin = $numero_codigos;
        }
        $codigos_restantes = $numero_codigos - $num_fin;
    }

    $links_meta = get_prev_and_next($numero_codigos, $codigos_restantes);

    /************************************************
     * Para header
     ************************************************/

    $title = "Comparte tus códigos amigo y códigos descuento - gana dinero, servicios y tiempo";
    $description = "Comparte códigos amigo y códigos de descuento con tus amigos y gana dinero, puntos o servicios ✅ - " . $author_web;
    $imagen_social = "https://www.codigoamigo.com/img/logo_social_codigoamigo_final.jpg";
    if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 1) {
        $title = $title . " | Página " . filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING);
        $description = "Mostrando del " . $num_inicio . " al " . $num_fin . " de un total de " . $lista_codigos->num . " códigos de descuento. " . $description;
    }
    $title_social = $title;
    $description_social = $description;

    $name_page = "home";

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/main.php';



});

$app->post('/google_sign', function ($request, $respon) {

    $respon = $respon->withHeader('Content-Type', 'application/json');

    global $author_web, $detect, $num_inicio;

    ob_start();
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/google-sign-in.php';
    $payload = ob_get_clean();
    $trimmedPayload = trim($payload);

    if ($trimmedPayload === '') {
        $trimmedPayload = json_encode([
            'success' => false,
            'error' => 'Respuesta vacía del servicio de autenticación'
        ]);
        error_log('[google_sign route] Respuesta vacía después de incluir google-sign-in.php');
    } elseif ($trimmedPayload[0] !== '{' && $trimmedPayload[0] !== '[') {
        error_log('[google_sign route] Respuesta inesperada: ' . substr($trimmedPayload, 0, 400));
    }

    $respon->getBody()->write($trimmedPayload);

    return $respon;

});


$app->get('/api_final', function ($request, $respon) {

    // Set response header to JSON
    $respon = $respon->withHeader('Content-Type', 'application/json');

    // Get query parameters
    $method = $_REQUEST["method"] ?? '';
    $id = $_REQUEST['id'] ?? '';

    // Handle different API methods
    if ($method == 'destacados') {
        $lista_destacados = dameDestacados();
        return $respon->withJSON($lista_destacados);
    } elseif ($method == 'dameDetalle' && $id) {
        $lista_codigos = dameDetalle($id);
        return $respon->withJSON($lista_codigos);
    }

    // Return error for invalid/missing method
    return $respon->withJSON([
        'error' => 'Invalid method or missing parameters'
    ], 400);
});




$app->get('/registro', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    if ($_SESSION["user_id"] != "") {
        echo "<script> window.location.href = 'https://www.codigoamigo.com' </script>";
    }

    $title = "Registrate en la web para acceder a cientos de códigos amigo y códigos descuento";
    $description = "Miles de códigos amigo te esperan en " . $author_web;

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/registro.php';

});

$app->any('/bienvenido', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    $title = "Código Amigo y Códigos Descuento";
    $description = "La única web donde puedes compartir tus códigos - " . $author_web;

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/bienvenido.php';

});


$app->get('/bienvenido_de_nuevo', function ($request, $respon) {

    global $author_web;

    $title = "Bienvenido a Código Amigo";
    $description = "La única web donde puedes compartir tus códigos - " . $author_web;

    // Obtener el código de activación
    $codigo_recibido = isset($_GET['codigo']) ? htmlspecialchars($_GET['codigo'], ENT_QUOTES, 'UTF-8') : null;
    
    if (!$codigo_recibido) {
        echo "Error: Código de activación no proporcionado";
        die;
    }

    // Corregir espacios por + para la desencriptación
    $cadena_encriptada_correcta = str_replace(" ", "+", $codigo_recibido);
    
    // Desencriptar el código para obtener el email del usuario
    $email_usuario = desencriptar($cadena_encriptada_correcta);
    
    if (!$email_usuario) {
        echo "Error: Código de activación inválido o expirado";
        die;
    }

    // Activar el usuario
    try {
        activeUserToLogin($email_usuario);
        
        // Verificar que la activación fue exitosa
        $collection_usuarios = getCollectionUsuarios();
        $usuario = $collection_usuarios->findOne(['mail' => $email_usuario]);
        
        if ($usuario && $usuario['estado'] == 1) {
            // Usuario activado correctamente, mostrar página de bienvenida
            include_once __DIR__ . '/public/bienvenido_de_nuevo.php';
        } else {
            echo "Error: No se pudo activar el usuario";
            die;
        }
        
    } catch (Exception $e) {
        error_log("Error activando usuario: " . $e->getMessage());
        echo "Error: No se pudo activar el usuario. Inténtalo de nuevo.";
        die;
    }

});

/* MIS CÓDIGOS */

$app->get('/felicidades', function ($request, $respon, $args) {

    global $author_web;
    global $ubicacion_actual, $show_adsense, $show_addthis;
    global $rating_count_rs, $rating_value_rs, $url_logo_rs, $url_marca_rs, $title_marca_rs;

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/felicidades.php';

});

/* MIS CÓDIGOS */

$app->get('/felicidades_splash', function ($request, $respon, $args) {


    global $author_web;
    global $ubicacion_actual, $show_adsense, $show_addthis;
    global $rating_count_rs, $rating_value_rs, $url_logo_rs, $url_marca_rs, $title_marca_rs;

    //     echo "<pre>";
//     print_r($request);
//     print_r($_REQUEST['session_id']);

    $_SESSION['session_id'] = $_REQUEST['session_id'];

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/felicidades_splash.php';

});

$app->get('/destaca', function ($request, $respon, $args) {

    global $author_web;
    global $ubicacion_actual, $show_adsense, $show_addthis;
    global $rating_count_rs, $rating_value_rs, $url_logo_rs, $url_marca_rs, $title_marca_rs;


    global $anula_adsense;

    $show_adsense = 0;
    $show_addthis = 0;
    $anula_adsense = true; // Esta variable será leída por el header para no mostrar Adsense

    //     $u = getObjectUser('_id', $codigo_to_show["id_usuario"]);
//     if($u && $u != "") { $info_user = get_array_de_usuario($u); }
//     $marca_codigo = getObjectMarca('nombre_clave', $codigo_to_show["marca"]);

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/destaca.php';
    $show_addthis = 0;
    $show_adsense = 0;

});


$app->get('/estadisticas', function ($request, $respon, $args) {

    global $author_web;
    global $ubicacion_actual, $show_adsense, $show_addthis;
    global $rating_count_rs, $rating_value_rs, $url_logo_rs, $url_marca_rs, $title_marca_rs;

    $show_adsense = 0;
    $show_addthis = 0;


    //     $u = getObjectUser('_id', $codigo_to_show["id_usuario"]);
    //     if($u && $u != "") { $info_user = get_array_de_usuario($u); }
    //     $marca_codigo = getObjectMarca('nombre_clave', $codigo_to_show["marca"]);

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/estadisticas.php';
    $show_addthis = 0;
    $show_adsense = 0;

});


$app->any('/mis_codigos', function ($request, $respon) {
    global $author_web;

    $newURL = "https://www.codigoamigo.com/usuario_" . strtolower($_SESSION["username"]) . "_" . $_SESSION["user_id"];

    return $respon->withRedirect($newURL, 301);
});


$app->group('/usuario_marcas', function () use ($app) {

    $app->get('/{name}_{id}', function ($request, $respon, $args) {

        global $author_web, $show_adsense, $tipo_block_codigos, $datos_usuario, $detect;

        global $suma_mis_marcas, $suma_marcas, $lista_marcas, $arrMisMarcas, $nombre_pag;

        $nombre_pag = "usuario_sin_marcas";

        // Extraer el ID (última parte después del último guión bajo) y el nombre
        $full_name = $args["name"];
        $id = $args["id"];
        
        // Convertir el nombre de la URL de vuelta al formato original
        $nombre_original = str_replace('_', ' ', $full_name);
        
        $usuario = getObjectUser('_id', new \MongoDB\BSON\ObjectId($id));
        $datos_usuario = get_array_de_usuario($usuario);
        
        // Definir variables para el header
        $title = "Descubre nuevas marcas - " . $datos_usuario["username"];
        $description = "Explora las marcas que " . $datos_usuario["username"] . " aún no ha descubierto";
        $title_social = $title;
        $description_social = $description;
        $imagen_social = $datos_usuario["img"];
        $links_meta = "";

        $lista_marcas = getMarcas(null);
        //$lista_marcas = iterator_to_array($lista_marcas);

        $listado_codigos = get_all_listado_codigos_by_user('estado', 0, $datos_usuario["_id"]);

        $num_codigos = $listado_codigos["total_number"];



        /* Marcas */
        foreach ($listado_codigos as $codigo) {
            // Convertir objeto a array si es necesario
            if (is_object($codigo)) { $codigo = (array)$codigo; }
            
            if (!$arrMisMarcas[$codigo["marca"]]) {
                $arrMisMarcas[$codigo["marca"]] = $codigo;
                $suma_mis_marcas++;
            }
        }

        $suma_marcas = count($lista_marcas);



        include_once $_SERVER['DOCUMENT_ROOT'] . '/public/usuario_marcas_que_no_tienes.php';

    });


});

$app->group('/usuario', function () use ($app) {
    $app->get('_{name}_{id}', function ($request, $respon, $args) {
        global $author_web, $show_adsense, $tipo_block_codigos, $datos_usuario;

        // Convertir el nombre de la URL de vuelta al formato original
        $nombre_original = str_replace('_', ' ', $args["name"]);

        // 1. Obtener usuario
        $usuario = getObjectUser('_id', new \MongoDB\BSON\ObjectId($args["id"]));
        $datos_usuario = get_array_de_usuario($usuario);

        // 2. Configurar paginación
        $page_param = filter_input(INPUT_GET, 'page', FILTER_SANITIZE_STRING);
        $page = $page_param !== null ? (int) $page_param : 1;
        $per_page = 20;
        $offset = ($page - 1) * $per_page;

        // 3. Obtener códigos con límite
        $estado_param = filter_input(INPUT_GET, 'estado', FILTER_SANITIZE_STRING);
        
        if ($estado_param === 'activos') {
            $estado = 0; // Solo activos
        } elseif ($estado_param === 'inactivos') {
            $estado = array('$in' => [-1, 1]); // Solo inactivos
        } elseif ($estado_param === 'borrados') {
            $estado = -2; // Solo borrados
        } elseif ($estado_param === 'all') {
            $estado = array('$in' => [0, -1, 1, -2]); // Todos los estados
        } else {
            // Por defecto: mostrar todos excepto borrados (comportamiento original)
            // pero permitir ver borrados con ?borrados=1
            if ($_REQUEST["borrados"] == 1) {
                $estado = array('$in' => [0, -1, 1, -2]); // Todos incluyendo borrados
            } else {
                $estado = array('$in' => [0, -1, 1]); // Activos + inactivos
            }
        }

        // Consulta optimizada con límite y skip
        $filter = [
            'estado' => $estado,
            'id_usuario' => $datos_usuario["_id"]
        ];

        $options = [
            'limit' => 200,
            'skip' => $offset,
            'sort' => ['_id' => -1]
        ];

        $listado_codigos = get_all_listado_codigos_array($filter, $options);


        $num_codigos = $listado_codigos["total_number"];


        // 4. Optimizar obtención de marcas
        $marca_names = [];
        $marca_keys = array_unique(array_column($listado_codigos['results'], 'marca'));

        // Obtener todas las marcas necesarias en una sola consulta
        $marcas = [];
        foreach ($marca_keys as $marca_key) {
            $marca = getObjectMarca('nombre_clave', $marca_key);
            if ($marca) {
                $marcas[$marca_key] = $marca;
            }
        }

        // Construir string de marcas
        foreach ($listado_codigos['results'] as $codigo) {
            if (is_object($codigo)) { $codigo = (array)$codigo; }
            if (isset($marcas[$codigo["marca"]])) {
                $marca_names[] = $marcas[$codigo["marca"]]["nombre"];
            }
        }
        $marca_str = implode(', ', array_slice($marca_names, 0, 5));

        // 5. Determinar tipo de visualización
        $tipo_block_codigos = ($_SESSION["user_id"] == $datos_usuario["id_string"])
            ? "mis_codigos"
            : "normal";

        // 6. Preparar datos para la vista
        $title = "Descubre mis " . $listado_codigos['total_number'] . " códigos amigo";
        $description = $usuario["username"] . " tiene " . $listado_codigos['total_number'] .
            " códigos de marcas como " . $marca_str;
        $imagen_social = $datos_usuario["img"];

        // 7. Deshabilitar adsense para mejor rendimiento
        $show_adsense = 0;

        // 8. Incluir la vista apropiada
        if ($tipo_block_codigos == 'mis_codigos' && !$_REQUEST["ext"]) {
            include_once $_SERVER['DOCUMENT_ROOT'] . '/public/mis_codigos.php';
        } else {
            include_once $_SERVER['DOCUMENT_ROOT'] . '/public/mis_codigos_externos.php';
        }
    });
});

/* EDITAR PERFIL */

$app->get('/usuario', function ($request, $respon) {


    /************************************************
     * Para header
     ************************************************/

    global $data_usuario, $author_web;

    $title = "Panel del usuario de " . $data_usuario["username"];
    $description = "Miembro de la comunidad de " . $GLOBALS["author"];

    /************************************************
     * Permiso entrada
     ************************************************/

    if (!$_SESSION["user_id"] || $_SESSION["user_id"] == "") {
        echo "<script> window.location.href = 'https://www.codigoamigo.com' </script>";
    } else {
        include_once $_SERVER['DOCUMENT_ROOT'] . '/public/usuario.php';
    }

});

$app->get('/chat', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/chat_usuario.php';
    return $respon;
});

$app->get('/chat-usuario', function ($request, $respon) {
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/chat_usuario.php';
    return $respon;
});

/********************************************************************
 * MARCA
 *******************************************************************/
$app->get('/listado_marcas', function ($request, $respon, $args) {
    return $respon->withRedirect("https://www.codigoamigo.com/listado-marcas", 301);
    die;
});

$app->get('/listado-marcas', function ($request, $respon, $args) {

    global $author_web;

    $title = "Nuestras marcas";
    $description = "Lista de nuestras marcas - " . $GLOBALS["author"];
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/listado_marcas.php';

});



$app->any('/codigos-de-{marca}-en-{provincia}', function ($request, $respon, $args) {

    global $provincia;

    $provincia = $args["provincia"];


    $marca = getObjectMarca('nombre_clave', $args["marca"]);

    /*REDIRECT A LA PAGINA DEL CODIGO*/
    $url_marca_rs = "https://www.codigoamigo.com/de-" . $marca["nombre_clave"];
    return $respon->withRedirect($url_marca_rs, 301);
    die;

    $array_filtro = array("marca" => $marca["nombre_clave"]);
    $array_filtro = array_merge($array_filtro, array("provincia" => strtoupper($args["provincia"])));
    $array_filtro = array_merge($array_filtro, array("estado" => array('$in' => [0, -1, 1])));
    $array_filtro = array_merge($array_filtro, array("destacado" => array('$ne' => 0)));

    $array_skip = array("limit" => 13);
    $array_skip = array_merge($array_skip, array("sort" => array('destacado' => -1)));

    //     'limit' => $limit,
//     'skip' => $skip,
//     'sort' => ['destacado' => -1, '_id' => -1],

    /* Listado a mostrar */
    $lista_codigos_patrocinados_pre = get_all_listado_codigos_array($array_filtro, $array_skip);
    $lista_codigos_patrocinados = $lista_codigos_patrocinados_pre["results"];

    $GLOBALS["actual_url_limpia"] = "https://www.codigoamigo.com/de-" . $marca["nombre_clave"];

    $title = "Códigos Descuento de " . $marca["nombre"] . " en " . $args["provincia"];
    $description = $marca["descripcion"] . " - " . $GLOBALS["author"];

    $extra_texto = " en " . $args["provincia"];

    $titulo_pagina = "Códigos Descuento y Códigos Amigo de " . $marca["nombre"] . " en " . $args["provincia"];



    /*
     * GET CODIGOS POR MARCA
     */

    //$all_codigos_por_marca = order_listado_codigos_localizacion($marca);

    $array_filtro = array("marca" => $marca["nombre_clave"]);
    $array_filtro = array_merge($array_filtro, array("provincia" => strtoupper($args["provincia"])));
    $array_filtro = array_merge($array_filtro, array("estado" => array('$in' => [0, -1, 1])));
    $array_filtro = array_merge($array_filtro, array("destacado" => 0));


    $array_skip = array("limit" => 13);

    /* Listado a mostrar */
    $lista_muestra_pre = get_all_listado_codigos_array($array_filtro, $array_skip);


    $lista_muestra = $lista_muestra_pre["results"];
    $numero_codigos = $lista_muestra_pre["total_number"];

    /* Listado a mostrar */

    //     $lista_codigos = get_all_listado_codigos_filtro('marca', $marca["nombre_clave"], 13, $skip);

    //     $lista_codigos = array_merge($array = array_slice($lista_codigos_patrocinados, 0, 3),$lista_codigos);


    //$lista_muestra = $all_codigos_por_marca[$args["provincia"]][$args["provincia"]];


    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/marca_filtro.php';

});

$app->any('/codigos-de-{marca}-de-{mes}-del-{any}', function ($request, $respon, $args) {


    $marca = getObjectMarca('nombre_clave', $args["marca"]);


    /* 301 a las paginas de año*/


    /*REDIRECT A LA PAGINA DEL CODIGO*/
    $url_marca_rs = "https://www.codigoamigo.com/de-" . $marca["nombre_clave"];
    return $respon->withRedirect($url_marca_rs, 301);
    die;




    $GLOBALS["actual_url_limpia"] = "https://www.codigoamigo.com/de-" . $marca["nombre_clave"];

    $title = "Códigos Descuento de " . $marca["nombre"] . " de " . $args["mes"] . " de " . $args["any"];
    $description = $marca["descripcion"] . " - " . $GLOBALS["author"];

    $extra_texto = " de " . $args["mes"] . " de " . $args["any"];

    $titulo_pagina = "Códigos Descuento y Códigos Amigo de " . $marca["nombre"] . " de " . $args["mes"] . " del " . $args["any"];

    $all_codigos_por_marca = order_listado_codigos($marca);
    $numero_codigos = count($all_codigos_por_marca);

    $lista_muestra = $all_codigos_por_marca[$args["any"]][$args["mes"]];

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/marca_filtro.php';

});


$app->get('/de-', function ($request, $respon, $args) {

    include_once $_SERVER['DOCUMENT_ROOT'] . '/404.php';

    return $respon->withHeader('Content-Type', 'text/html')
        ->withStatus(404);

});

$app->get('/de-{marca}', function ($request, $respon, $args) {


    global $author_web;
    global $ubicacion_actual;
    global $rating_count_rs, $rating_value_rs, $url_logo_rs, $url_marca_rs, $title_marca_rs, $codigo_existente;

    global $name_page;


    /************************************************
     * REDIRECTS y 301
     ************************************************/

    $newURL = strtok($GLOBALS["actual_url"], '?');
    $arrayUrlToMove = array(
        "https://www.codigoamigo.com/de-ingdirect" => "https://www.codigoamigo.com/de-ing",
        "https://www.codigoamigo.com/de-bancoing" => "https://www.codigoamigo.com/de-ing",
        "https://www.codigoamigo.com/de-diasupermercadoonline" => "https://www.codigoamigo.com/de-dia",
        "https://www.codigoamigo.com/de-repsolwaylet" => "https://www.codigoamigo.com/de-repsol-waylet",
        "https://www.codigoamigo.com/de-descuentoenrepsolwaylet" => "https://www.codigoamigo.com/de-repsol-waylet",
    );

    foreach ($arrayUrlToMove as $viejo => $nuevo) {
        if ($newURL == $viejo) {
            return $respon->withRedirect($nuevo, 301);
            die;
        }
    }

    /************************************************
     * CÓDIGOS DE MARCA
     ************************************************/
    $marca = getObjectMarca('nombre_clave', $args["marca"]);




    if ($marca["imagen"] == 'Sin imagen') {
        $marca["imagen"] = "https://www.codigoamigo.com/img/logo_codigoamigo.png";
    }





    /* SI TIENE CODIGO Y NO ESTA LOGUEADO*/
    //     if(filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING) && !$_SESSION["user_id"] && $marca["nombre_clave"]!='bookingcom'){


    //         /*REDIRECT A LA PAGINA DEL CODIGO*/
//         $url_marca_rs = "https://www.codigoamigo.com/de-".$marca["nombre_clave"];

    //         return $respon->withRedirect($url_marca_rs, 301); die;

    //     }


    if ($marca["nombre_clave"]) {

        /* Para saber cuantos codigos tengo que saltar segun la página donde estoy */
        $skip = get_skip_in_pagination();
        $skip_patrocinados = get_skip_patrocinados_in_pagination();

        if (!filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING)) {

            /* Listado PATROCINADOS */
            $array_filtro = array("marca" => $marca["nombre_clave"]);
            $array_filtro = array_merge($array_filtro, array("estado" => array('$in' => [0, -1, 1])));
            $array_filtro = array_merge($array_filtro, array("destacado" => array('$ne' => 0)));

            $array_skip = array("limit" => 7);
            $array_skip = array_merge($array_skip, array("skip" => $skip_patrocinados));
            $array_skip = array_merge($array_skip, array("sort" => array('destacado' => -1)));

            $lista_codigos_patrocinados_pre = get_all_listado_codigos_array($array_filtro, $array_skip);
            $lista_codigos_patrocinados = $lista_codigos_patrocinados_pre["results"];
            $skip_patrocinados = $lista_codigos_patrocinados_pre["total_number"];

            //         echo $lista_codigos_patrocinados_pre["total_number"];die;

            //         echo "<pre>";
//         print_r($lista_codigos_patrocinados_pre);
//         die;


            /* Listado NORMAL */
            $array_filtro = array("marca" => $marca["nombre_clave"]);
            $array_filtro = array_merge($array_filtro, array("estado" => array('$in' => [0, -1, 1])));
            $array_filtro = array_merge($array_filtro, array("destacado" => 0));


            $array_skip = array("limit" => (30 + $skip_patrocinados));
            $array_skip = array_merge($array_skip, array("skip" => $skip_patrocinados));

            //TOMO LOS CODIGOS
            $lista_codigos_pre = get_all_listado_codigos_array($array_filtro, $array_skip);

            $lista_codigos = $lista_codigos_pre["results"];
            $numero_codigos = $lista_codigos_pre["total_number"];

            //         echo "<pre>";
//         print_r($lista_codigos);
// die;

            $total_pag = (intval($numero_codigos / 10)) + 1;

            //$lista_codigos = get_all_listado_codigos_filtro('marca', $marca["nombre_clave"], 16, $skip);


            if ($lista_codigos_patrocinados) {
                $lista_codigos = array_merge(array_slice($lista_codigos_patrocinados, 0, 1), $lista_codigos);
            }

            $imagen_social = $marca["imagen"];

            // Inicializar $codigo_existente siempre, incluso si el usuario no tiene código
            $codigo_existente = null;
            if (isset($_SESSION["user_id"]) && !empty($_SESSION["user_id"])) {
                $codigo_existente = get_codigos_by_user_brand($marca["nombre_clave"], $_SESSION["user_id"]);
            }

        } else {


            $obj_id_codigo = new \MongoDB\BSON\ObjectId(filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING));
            $lista_codigos = getCodeByID_prelista($obj_id_codigo);
            $codigo_to_show = getCodeByID($obj_id_codigo);
            if (is_object($codigo_to_show)) { $codigo_to_show = (array)$codigo_to_show; }
            
            // Incrementar contador de vistas
            añadir_vista_codigo($codigo_to_show);

            $u = getObjectUser('_id', $codigo_to_show["id_usuario"] ?? null);
            //     if($u && $u != "") { $info_user = get_array_de_usuario($u); }
//     $marca_codigo = getObjectMarca('nombre_clave', $codigo_to_show["marca"]);

            $numero_codigos = 1;
            $total_pag = 1;


            $imagen_social = $marca["imagen"];

            $codigo_descripcion = is_object($codigo_to_show) ? $codigo_to_show->descripcion : $codigo_to_show["descripcion"];
            $description = recorta_texto_pos($codigo_descripcion, "250", "..");
        }

        if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 999 || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > $total_pag || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) == 1) {
            return $respon->withRedirect($newURL, 301);
        }

        if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) == "") {
            $num_inicio = 1;
            $num_fin = 20;
            $codigos_restantes = $numero_codigos;
        } else {
            $num_inicio = (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10) - 9;
            $num_fin = filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10;
            if ($num_fin > $numero_codigos) {
                $num_fin = $numero_codigos;
            }
            $codigos_restantes = $numero_codigos - $num_fin;
        }

        $links_meta = get_prev_and_next($numero_codigos, $codigos_restantes);


        /************************************************
         * Para header
         ************************************************/

        /*
         * Del $lista_codigos_total, buscamos el código con el mayor beneficio
         */

        $ubicacion_actual = "marca123";
        $num_beneficio_descuento = 0;
        $num_beneficio_euros = 0;
        $num_beneficio_minutos = 0;

        if ($marca["nombre_clave"] == 'lixsaai') {
            $title_marca_rs = "Códigos de Descuento y Ofertas de " . $marca["nombre"] . " - Ahorra hasta 50€";
        } else {
            $title_marca_rs = "Códigos Amigo y códigos descuento de " . $marca["nombre"];
        }
        $url_marca_rs = "https://www.codigoamigo.com/de-" . $marca["nombre_clave"];
        $url_logo_rs = $marca["imagen"];
        if (strpos($url_logo_rs, 'codigoamigo.com') !== false) {
            $url_logo_rs = "https://www.codigoamigo.com" . $marca["imagen"];
        }
        $rating_count_rs = $numero_codigos;
        $rating_value_rs = 4 + ($numero_codigos / 1000);

        $lista_descuentos = [];
        $lista_euros = [];
        $lista_minutos = [];

        foreach ($lista_codigos as $ita) {
            if (is_object($ita)) { $ita = (array)$ita; }
            $tipo_desc = isset($ita["tipo_descuento"]) ? $ita["tipo_descuento"] : null;
            if ($tipo_desc === "% de descuento") {
                $lista_descuentos[] = $ita;
            } else if ($tipo_desc === "euros") {
                $lista_euros[] = $ita;
            } else if ($tipo_desc === "minutos gratis") {
                $lista_minutos[] = $ita;
            }
        }


        if (count($lista_descuentos) > 0) {
            foreach ($lista_descuentos as $d) {
                if ($d["num_beneficio"] > $num_beneficio_descuento) {
                    $num_beneficio_descuento = $d["num_beneficio"];
                }
            }
        }

        if (count($lista_euros) > 0) {
            foreach ($lista_euros as $e) {
                if ($e["num_beneficio"] > $num_beneficio_euros) {
                    $num_beneficio_euros = $e["num_beneficio"];
                }
            }
        }

        if (count($lista_minutos) > 0) {
            foreach ($lista_minutos as $m) {
                if ($m["num_beneficio"] > $num_beneficio_minutos) {
                    $num_beneficio_minutos = $m["num_beneficio"];
                }
            }
        }

        $string_mejor_codigo = "";

        if ($num_beneficio_euros > 0) {
            $string_mejor_codigo = "【 ahorra " . $num_beneficio_euros . "€ 】";
        } elseif ($num_beneficio_descuento > 0) {
            $string_mejor_codigo = $num_beneficio_descuento . " % DESC.";
        } else {
            $string_mejor_codigo = $num_beneficio_minutos . " MIN. GRATIS";
        }

        setlocale(LC_ALL, "es_ES");
        $string = date('d/m/Y');
        $date = DateTime::createFromFormat("d/m/Y", $string);
        //▷ CUPÓN WEBEMPRESA 【 ¡25% Descuento YA! 】» 2019

        // Array de meses en español
        $meses_es = [
            1 => 'Enero', 2 => 'Febrero', 3 => 'Marzo', 4 => 'Abril',
            5 => 'Mayo', 6 => 'Junio', 7 => 'Julio', 8 => 'Agosto',
            9 => 'Septiembre', 10 => 'Octubre', 11 => 'Noviembre', 12 => 'Diciembre'
        ];
        
        $string_fecha = " " . $meses_es[(int)$date->format('n')] . " " . $date->format('Y');


        if (filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING)) {

            $title = "Gana con mi Código Amigo de " . $marca["nombre"] . " " . $string_mejor_codigo;

        } else {


            if ($marca["nombre_clave"] == 'bookingcom') {
                $pre_txt = "Códigos Descuento ";
            } elseif ($marca["nombre_clave"] == 'fever') {
                $pre_txt = "Cupones ";
            } elseif ($marca["nombre_clave"] == 'glovo') {
                $pre_txt = "Cupones Descuento ";
            } elseif ($marca["nombre_clave"] == 'jazztel') {
                $pre_txt = "Planes amigo ";
            } elseif ($marca["nombre_clave"] == 'playfulbet') {
                $pre_txt = "Cupones ";
            } elseif ($marca["nombre_clave"] == 'cheerz') {
                $pre_txt = "Códigos Descuento ";
            } elseif ($marca["nombre_clave"] == 'n26') {
                $pre_txt = "Códigos Promocionales ";
            } elseif ($marca["nombre_clave"] == 'mitto') {
                $pre_txt = "Códigos Invitación ";
            } elseif ($marca["nombre_clave"] == 'traderepublic') {
                $pre_txt = "Código Invitación ";
            } elseif ($marca["nombre_clave"] == 'lixsaai') {
                $pre_txt = "Códigos de Descuento ";
            } else {
                $pre_txt = "Cupones descuento ";
            }


            //$title = "🥇 Códigos Amigo de ".$marca["nombre"]." - ".$string_mejor_codigo . " en " . $numero_codigos." - Cupones descuento".$string_fecha;
            //$title = "🥇 ".$pre_txt.$marca["nombre"]." ".$string_mejor_codigo . " cupones descuento »" . $string_fecha;
            $title = $pre_txt . $marca["nombre"] . "" . $string_mejor_codigo . "" . trim($string_fecha);


        }

        if (!$description) {


            $desc_icon = "✅";


            if ($marca["nombre_clave"] == 'lixsaai') {
                $description = "Ahorra hasta 50€ con códigos de descuento de " . $marca["nombre"] . ". Códigos promocionales para servicios de IA y automatización válidos para" . $string_fecha . "$desc_icon - ¡Automatiza tu negocio y ahorra dinero!";
            } else {
                $description = trim($string_mejor_codigo) . " con tu de código invitación " . $marca["nombre"] . ". Códigos descuento y cupones descuento válidos para" . $string_fecha . "$desc_icon - ¡Aprovecha y gana dinero";
            }

            //Ahorra 200€ con tu código invitación Trade Republic. Códigos descuento y cupones válidos para julio 2024. ¡Aprovecha y gana dinero ahora!

            if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 1) {
                $title = $title . " | Página " . filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING);
                $description = "Listado de " . $numero_codigos . " códigos amigo y códigos descuento (mostrando del " . $num_inicio . " al " . $num_fin . ") sobre " . $marca["nombre"] . " ✅. No te pierdas ninguno de los " . $numero_codigos . " códigos de descuento sobre " . $marca["nombre"] . " - " . $author_web;
            }
        }
        if (!$title_social) {
            $title_social = $title;
        }
        $description_social = $description;

        $name_page = "marca";

        // Incluir funciones modernas necesarias para marca_moderna.php
        include_once __DIR__ . '/myphp/_header_modern.php';
        include_once __DIR__ . '/myphp/funciones_usuario.php';
        include_once __DIR__ . '/myphp/funciones_html.php';

        include_once $_SERVER['DOCUMENT_ROOT'] . '/public/marca_moderna.php';


    } elseif (!$marca["nombre_clave"]) {


        if (strstr($args["marca"], "movig")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-muving')->withStatus(301);
        } elseif (strstr($args["marca"], "acciona")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-acciona')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "booking")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "repsol") || strstr($args["marca"], "waylet")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-repsol-waylet')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "airbnb")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-airbnb')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "playfulbet")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-playfulbet')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "muving")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-muving')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } elseif (strstr($args["marca"], "mitto")) {
            return $respon->withRedirect('https://www.codigoamigo.com/de-mitto')->withStatus(301);
            //return $ap-$response->withRedirect('https://www.codigoamigo.com/de-bookingcom')->withStatus(301);
        } else {

            if (extension_loaded('newrelic')) {
                newrelic_add_custom_parameter("url_completa", $GLOBALS["actual_url"]);
                newrelic_add_custom_parameter("linea", __FILE__ . ":" . __LINE__);
                newrelic_notice_error("CODIGOAMIGO - Marca inexistente " . $GLOBALS["actual_url"]);
            }

            include_once $_SERVER['DOCUMENT_ROOT'] . '/404.php';

            return $respon->withHeader('Content-Type', 'text/html')
                ->withStatus(404);



        }

    }

});

$app->get('/que-es-{marca}', function ($request, $respon, $args) {

    global $que_es;

    $que_es = 1;

    $arrayUrlToMove = array(
        "https://www.codigoamigo.com/que-es-repsolwaylet" => "https://www.codigoamigo.com/que-es-repsol-waylet",
        "https://www.codigoamigo.com/que-es-descuentoenrepsolwaylet" => "https://www.codigoamigo.com/que-es-repsol-waylet",
    );

    foreach ($arrayUrlToMove as $viejo => $nuevo) {
        if ($GLOBALS["actual_url"] == $viejo) {
            return $respon->withRedirect($nuevo, 301);
            die;
        }
    }

    $marca = getObjectMarca('nombre_clave', $args["marca"]);
    $title = $marca["nombre"];
    $description = $marca["descripcion"] . " - " . $GLOBALS["author"];

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/blog_marca.php';

});



/********************************************************************
 * CONTACTO
 *******************************************************************/

$app->any('/contacto', function ($request, $respon) {

    global $author_web, $noindex, $email;

    $noindex = 1;

    $title = "Contacto";
    $description = "Comunícate con el equipo de " . $author_web;
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/contacto.php';

});

$app->any('/contacto_empresa', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    $title = "Contacto para empresas";
    $description = "Contacta con el equipo de " . $author_web;
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/contacto_empresa.php';

});

/********************************************************************
 * RGPD
 *******************************************************************/

$app->get('/politica-de-privacidad', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    $title = "Política de privacidad y protección de datos";
    $description = "Política de privacidad y protección de datos de " . $author_web;
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/politica_de_privacidad.php';

});

$app->get('/politica-de-cookies', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    $title = "Política de cookies";
    $description = "Política de cookies de " . $author_web;
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/politica_de_cookies.php';

});

$app->get('/aviso-legal', function ($request, $respon) {

    global $author_web, $noindex;

    $noindex = 1;

    $title = "Condiciones de uso";
    $description = "Condiciones de uso de " . $author_web;
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/aviso_legal.php';

});

/********************************************************************
 * CÓDIGO
 *******************************************************************/

$app->any('/busqueda', function ($request, $respon) {

    // Incluir configuración del rediseño
    // require_once __DIR__ . '/redesign_config.php'; // Archivo no existe en backup original
    
    // if (is_redesign_enabled()) { // Función no disponible sin redesign_config.php
    //     include_once $_SERVER['DOCUMENT_ROOT'] . '/public/busqueda_real.php';
    //     return $respon;
    // }

    global $author_web;

    $title = "Resultados de búsqueda";
    $description = "Resultados de búsqueda de " . $author_web;

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/busqueda.php';

});

$app->get('/nuevo_codigo', function ($request, $respon) {

    global $author_web, $show_adsense, $name_page;

    // Validar que el usuario esté logueado
    if (!isset($_SESSION["user_id"]) || empty($_SESSION["user_id"])) {
        $_SESSION['msg_error'] = "Debes iniciar sesión para publicar códigos";
        return $respon->withRedirect($GLOBALS["website"] . "login");
    }

    $show_adsense = 0;

    $title = "Insertar nuevo código";
    $description = "Unete a la comunidad de " . $author_web;

    $name_page = "nuevo_codigo";

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/publicar_codigo.php';

});



$app->get('/modificar_codigo/{codigo_id}', function ($request, $response, $args) {
    global $author_web, $show_adsense, $name_page, $detect;
    session_start(); if (!isset($_SESSION["user_id"])) { header("Location: login.php"); exit; } if (!isset($_SESSION["user_id"])) { header("Location: login.php"); exit; }
    $show_adsense = 0;
    $title = "Modificar Código";
    $description = "Modifica el código existente en " . $author_web;
    $name_page = "modificar_codigo";

    $codigo_id = $args['codigo_id'];
    $obj_id_codigo = new \MongoDB\BSON\ObjectId($codigo_id);
    $codigo_to_show = getCodeByID($obj_id_codigo);
    
    // Convertir objeto a array si es necesario (como se hace en otras partes del código)
    if (is_object($codigo_to_show)) { 
        $codigo_to_show = (array)$codigo_to_show; 
    }

    if (!$codigo_to_show) {
        $_SESSION['msg_error'] = "El código solicitado no existe";
        return $response->withRedirect($GLOBALS["website"]);
    }

    if (!$_SESSION["user_id"]) {
        $_SESSION['msg_error'] = "Debes iniciar sesión para poder modificar códigos";
        return $response->withRedirect($GLOBALS["website"]);
    }

    // Convertir objeto a array si es necesario
    if (is_object($codigo_to_show)) { 
        $codigo_to_show = (array)$codigo_to_show; 
    }
    
    // Normalizar id_usuario para comparación segura
    $codigo_user_id = isset($codigo_to_show["id_usuario"]) && is_object($codigo_to_show["id_usuario"]) 
        ? (string)$codigo_to_show["id_usuario"] 
        : ($codigo_to_show["id_usuario"] ?? null);
    
    if ($codigo_user_id != $_SESSION["user_id"]) {
        $_SESSION['msg_error'] = "No tienes permiso para modificar este código";
        return $response->withRedirect($GLOBALS["website"]);
    }

    // Verificar si el código está borrado y mostrar alerta
    if (isset($codigo_to_show["estado"]) && $codigo_to_show["estado"] == -2) {
        $_SESSION['msg_warning'] = "⚠️ Este código está marcado como borrado. Al guardar los cambios, se restaurará automáticamente.";
    }

    // El usuario está autorizado, cargar datos para edición
    $codigo_data = getCodeByID_prelista($obj_id_codigo);
    if (is_array($codigo_data) && count($codigo_data) > 0) {
        $codigo_data = $codigo_data[0];
    } elseif (is_object($codigo_data)) {
        // Si es un objeto, mantenerlo como objeto
        $codigo_data = $codigo_data;
    } else {
        $_SESSION['msg_error'] = "No se encontró el código solicitado";
        return $response->withRedirect($GLOBALS["website"]);
    }

    $numero_codigos = 1;
    $total_pag = 1;
    // Asegurar que $codigo_to_show es un array antes de acceder a sus elementos
    if (is_object($codigo_to_show)) { 
        $codigo_to_show = (array)$codigo_to_show; 
    }
    $description = recorta_texto_pos($codigo_to_show["descripcion"], "250", "..");
    
    // Cargar marca asociada y normalizar a array
    if (isset($codigo_to_show["marca"])) {
        $marca = get_object_marca('nombre_clave', $codigo_to_show["marca"]);
        if (is_object($marca)) { $marca = (array)$marca; }
    }
    $imagen_social = isset($marca["imagen"]) ? $marca["imagen"] : null;

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/publicar_codigo.php';
});

$app->post('/modificar_codigo/{codigo_id}', function ($request, $response, $args) {

    global $author_web, $show_adsense, $name_page;

    try {
        $title = "Código modificado";
        $description = "Nuevo código insertado a la web - " . $author_web;
        
        // Validar que el usuario esté logueado
        if (!isset($_SESSION["user_id"]) || empty($_SESSION["user_id"])) {
            $_SESSION['msg_error'] = "Debes iniciar sesión para poder modificar códigos";
            return $response->withRedirect($GLOBALS["website"]);
        }

        // Validar que el codigo_id sea válido
        if (!isset($args['codigo_id']) || empty($args['codigo_id'])) {
            $_SESSION['msg_error'] = "ID de código inválido";
            return $response->withRedirect($GLOBALS["website"]);
        }

        $_POST["codigo_id"] = $args['codigo_id'];
        
        // Validar que hay datos POST
        if (empty($_POST)) {
            $_SESSION['msg_error'] = "No se recibieron datos para modificar";
            return $response->withRedirect($GLOBALS["website"]);
        }

        // Validar campos requeridos
        $required_fields = ['codigo', 'descripcion', 'marca'];
        foreach ($required_fields as $field) {
            $field_value = filter_input(INPUT_POST, $field, FILTER_SANITIZE_STRING);
            if ($field_value === null || empty(trim($field_value))) {
                $_SESSION['msg_error'] = "El campo '$field' es requerido";
                return $response->withRedirect($GLOBALS["website"]);
            }
        }

        // Verificar si el código está borrado y restaurarlo automáticamente
        $codigo_id_obj = new \MongoDB\BSON\ObjectId($args['codigo_id']);
        $codigo_actual = getCodeByID($codigo_id_obj);
        
        if ($codigo_actual && isset($codigo_actual["estado"]) && $codigo_actual["estado"] == -2) {
            // El código está borrado, restaurarlo primero
            $db = createConnection();
            $collection = $db->selectCollection('codigos');
            
            $collection->updateOne(
                ['_id' => $codigo_id_obj],
                ['$set' => [
                    'estado' => 0,
                    'fecha_modificacion' => new \MongoDB\BSON\UTCDateTime(),
                    'updated_at' => new \MongoDB\BSON\UTCDateTime()
                ]]
            );
            
            // Recalcular visibilidad
            $codigo_id_string = (string)$codigo_id_obj;
            $marca_clave = $codigo_actual['marca'] ?? '';
            if ($marca_clave) {
                updateCodeVisibilityByPosition($codigo_id_string, $marca_clave);
                updateAllCodesVisibilityInBrand($marca_clave);
            }
        }

        // Intentar actualizar el código
        $update_result = updateExistingCode($_POST, $_SESSION["user_id"]);
        
        if (!$update_result) {
            $_SESSION['msg_error'] = "Error al modificar el código. Verifica que tengas permisos o que el código exista.";
            return $response->withRedirect($GLOBALS["website"]);
        }

        // Obtener el código actualizado
        $obj_id_codigo = new \MongoDB\BSON\ObjectId(filter_input(INPUT_POST, "codigo_id", FILTER_SANITIZE_STRING));
        $codigo = getCodeByID($obj_id_codigo);

        if (!$codigo) {
            $_SESSION['msg_error'] = "Error al obtener el código modificado";
            return $response->withRedirect($GLOBALS["website"]);
        }

        $url = $GLOBALS["website"] . "de-" . $codigo["marca"] . "?codigo=" . $codigo["_id"];
        $_SESSION["msg"] = "Código modificado correctamente";

        return $response->withRedirect($url);

    } catch (Exception $e) {
        // Log del error para debugging
        error_log("Error en modificar_codigo: " . $e->getMessage());
        
        $_SESSION['msg_error'] = "Error interno del servidor al modificar el código";
        return $response->withRedirect($GLOBALS["website"]);
    }
});

$app->post('/borrar_codigo/{codigo_id}', function ($request, $response, $args) {
    global $author_web;

    try {
        // Verificar que el usuario esté logueado
        if (!isset($_SESSION["user_id"]) || empty($_SESSION["user_id"])) {
            $_SESSION['msg_error'] = "Debes iniciar sesión para borrar códigos";
            return $response->withRedirect('/');
        }

        $codigo_id = $args['codigo_id'];

        // Verificar que el código existe y pertenece al usuario
        $codigo = getObjectCode('_id', $codigo_id);

        if (!$codigo) {
            $_SESSION['msg_error'] = "El código no existe";
            return $response->withRedirect('/');
        }

        if ($codigo['id_usuario'] !== $_SESSION["user_id"]) {
            $_SESSION['msg_error'] = "No tienes permisos para borrar este código";
            return $response->withRedirect('/');
        }

        // Borrar el código
        $collection = getCollectionCodigos();
        $result = $collection->deleteOne(['_id' => new MongoDB\BSON\ObjectId($codigo_id)]);

        if ($result->getDeletedCount() > 0) {
            $_SESSION['msg'] = "Código borrado correctamente";
        } else {
            $_SESSION['msg_error'] = "Error al borrar el código";
        }

        // Redirigir a la página de la marca
        $marca = getObjectMarca('nombre_clave', $codigo['marca']);
        $url_marca = "https://www.codigoamigo.com/de-" . $marca['nombre_clave'];

        return $response->withRedirect($url_marca);

    } catch (Exception $e) {
        error_log("Error al borrar código: " . $e->getMessage());
        $_SESSION['msg_error'] = "Error interno del servidor";
        return $response->withRedirect('/');
    }
});

$app->post('/codigo_insertado', function ($request, $respon) {

    global $author_web;

    $title = "Código añadido";
    $description = "Nuevo código insertado a la web - " . $author_web;
    if ($_POST) {
        $data = addNewCode($_POST, $_SESSION["user_id"]);
    }

    $codigo = getObjectCode('codigo', filter_input(INPUT_POST, "codigo_id", FILTER_SANITIZE_STRING));
    $url = $GLOBALS["website"] . "de-" . $codigo["marca"] . "?codigo=" . $codigo["_id"];



    $_SESSION["msg"] = "Codigo insertado";

    return $respon->withRedirect($url);

});

$app->get('/categoria', function ($request, $respon, $args) {

    $categoria = getObjectCategoria('nombre_clave', filter_input(INPUT_GET, "categoria", FILTER_SANITIZE_STRING));
    $title = "Códigos de amigo de " . $categoria["nombre"];
    $description = $categoria["descripcion"] . " - " . $GLOBALS["author"];
    include __DIR__ . '/../public/categoria.php';

});

$app->get('/{categoria}-comparte-y-gana', function ($request, $respon, $args) {


    $categoria = getObjectCategoria('nombre_clave', $args["categoria"]);
    if (is_object($categoria)) { $categoria = (array)$categoria; }

    $lista_marcas = getListObjectsMarca('categoria_clave', $categoria["nombre_clave"] ?? '');



    $listado_marcas_tab = $lista_marcas;
    $listado_marcas_panel = $lista_marcas;

    $skip = get_skip_in_pagination();

    /* Listado a mostrar */


    //         $lista_codigos = get_listado_codigos('clave_categoria', $categoria["nombre_clave"], 10, 0);
//         $numero_codigos = $lista_codigos->num;


    /* Listado a mostrar */

    $lista_codigos_patrocinados = array();

    $lista_codigos_patrocinados = get_all_listado_codigos_destacados('clave_categoria', $categoria["nombre_clave"], 10, 0);


    //         foreach($lista_marcas as $field => $marca_field){


    //             //echo $marca_field["nombre_clave"]."<br>";
//             //$lista_codigos_patrocinados = get_all_listado_codigos_destacados('marca', $marca["nombre_clave"], 13, $skip_patrocinados);

    //             $pre_lista = get_all_listado_codigos_destacados('marca', $marca_field["nombre_clave"], 10, 0);
//             /*echo "<pre>";
//             print_r($pre_lista);*/

    //             if($pre_lista){
//                 $lista_codigos_patrocinados = array_merge($pre_lista,$lista_codigos_patrocinados);
//             }

    //         }



    $newURL = strtok($GLOBALS["actual_url"], '?');
    $num_inicio = (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10) - 9;
    $num_fin = filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) * 10;
    if ($num_fin > $numero_codigos) {
        $num_fin = $numero_codigos;
    }
    $codigos_restantes = $numero_codigos - $num_fin;
    $total_pag = (intval($numero_codigos / 10)) + 1;
    if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 999 || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > $total_pag || filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) == 1) {
        return $respon->withRedirect($newURL, 301);
    }

    $links_meta = get_prev_and_next($numero_codigos, $codigos_restantes);

    $title = " Códigos amigo y códigos descuento sobre " . $categoria["nombre"];
    $description = "Listado de " . $lista_codigos->num . " códigos amigo sobre " . $categoria["descripcion"] . " ✅. No te pierdas ningún código de descuento sobre " . $categoria["descripcion"] . " - " . $GLOBALS["author"];

    if (filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING) > 1) {
        $title = $title . " | Página " . filter_input(INPUT_GET, "page", FILTER_SANITIZE_STRING);
        $description = "Listado de " . $lista_codigos->num . " códigos amigo (mostrando del " . $num_inicio . " al " . $num_fin . ") sobre " . $categoria["descripcion"] . " ✅. No te pierdas ningún código de descuento del total de " . $lista_codigos->num . " códigos de descuento. - " . $GLOBALS["author"];
    }
    include __DIR__ . '/../public/categoria.php';

});

$app->get('/listado_categorias', function ($request, $respon, $args) {
    return $respon->withRedirect("https://www.codigoamigo.com/listado-categorias", 301);
    die;
});

$app->get('/listado-categorias', function ($request, $respon, $args) {

    $title = "Nuestras categorías";
    $description = "Lista de nuestras categorías - " . $GLOBALS["author"];
    include __DIR__ . '/../public/listado_categorias.php';

});









/* ------------------------- USUARIO ----------------------- */



$app->get('/login', function ($request, $respon) {
    global $author_web, $noindex;

    $noindex = 1;

    if ($_SESSION["user_id"] != "") {
        echo "<script> window.location.href = 'https://www.codigoamigo.com' </script>";
        exit;
    }

    $title = "Iniciar sesión en " . $author_web;
    $description = "Accede a tu cuenta para gestionar tus códigos amigo";

    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/login.php';
});

$app->post('/login', function ($request, $respon, $args) {

    global $noindex;

    $noindex = 1;

    $mail_ = filter_input(INPUT_POST, "mail_login", FILTER_SANITIZE_STRING);
    $pass_ = filter_input(INPUT_POST, "pass_login", FILTER_SANITIZE_STRING);
    include __DIR__ . '/../php/login.php';
});

$app->any('/login_facebook', function ($request, $respon, $args) {

    global $noindex;

    $noindex = 1;

    $name = filter_input(INPUT_POST, "nombre_usuario", FILTER_SANITIZE_STRING);
    $mail = filter_input(INPUT_POST, "correo_usuario", FILTER_SANITIZE_STRING);
    $imagen = str_replace("http://", "https://", filter_input(INPUT_POST, "imagen_usuario", FILTER_SANITIZE_STRING));
    include __DIR__ . '/../php/login_facebook.php';
});

$app->any('/login_google', function ($request, $respon, $args) {

    global $noindex;

    $noindex = 1;

    $name = filter_input(INPUT_POST, "nombre_usuario", FILTER_SANITIZE_STRING);
    $mail = filter_input(INPUT_POST, "correo_usuario", FILTER_SANITIZE_STRING);
    $imagen = str_replace("http://", "https://", filter_input(INPUT_POST, "imagen_usuario", FILTER_SANITIZE_STRING));
    include __DIR__ . '/../php/login_google.php';
});

$app->get('/cambiar_password', function ($request, $respon) {
    global $noindex;

    $noindex = 1;

    $title = "Cambiar contraseña";
    $description = "Recupera la contraseña de tu usuario de " . $GLOBALS["author"];
    include __DIR__ . '/../public/cambiar_password.php';
});

$app->post('/cambio_password', function ($request, $response) {

    global $noindex;

    $noindex = 1;

    try {
        // Incluir archivos necesarios para las funciones de correo y usuario
        include_once __DIR__ . '/myphp/funciones_usuario.php';
        include_once __DIR__ . '/myphp/funciones_mail.php';
        include_once __DIR__ . '/inc/funciones.php';

        // Obtener el email del formulario de recuperación de contraseña
        $mail_ = filter_input(INPUT_POST, "mail", FILTER_SANITIZE_EMAIL);
        
        if (empty($mail_)) {
            return $response->withRedirect('/cambiar_password?msg_error=ok');
        }
        
        // Usar la variable $mail_ para buscar el usuario
        $usuario = getObjectUser('mail', $mail_);

        if (empty($usuario) || !is_array($usuario) || empty($usuario["username"])) {
            return $response->withRedirect('/cambiar_password?msg_error=ok');
        }

        if($usuario["estado"] == 0){ //SI ES 0 REENVIO ACTIVACION
            $usuario["correo"] = $usuario["mail"];
            $usuario["nombre"] = $usuario["username"];
            enviar_mail_activacion($usuario);
        } else {
            enviarMailRecuerdoPass($usuario);
        }
        
        return $response->withRedirect('/cambiar_password?msg=ok');
        
    } catch (Exception $e) {
        error_log("Error en cambio_password: " . $e->getMessage());
        return $response->withRedirect('/cambiar_password?msg_error=ok');
    }
});

$app->get('/nuevo_password', function ($request, $respon) {

    global $noindex;

    $noindex = 1;

    $title = "Cambio de contraseña";
    $description = "Cambia la contraseña de tu usuario de " . $GLOBALS["author"];
    
    /* filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING) es el correo encriptado del usuario que quiere confirmar su mail.*/
    $mail_encriptado = filter_input(INPUT_GET, "codigo", FILTER_SANITIZE_STRING);
    
    if (!$mail_encriptado) {
        // Si no hay código, redirigir a la página de recuperación
        return $respon->withRedirect('/cambiar_password?msg_error=invalid_code');
    }
    
    /* Hay errores en la desencriptación al encontrar espacios y convertirlos en +. Por eso,
     * corregimos estos + por espacios para que la desencriptación sea correcta. */
    $cadena_encriptada_correcta = str_replace(" ", "+", $mail_encriptado);
    
    /* Desencriptamos la cadena para poder trabajar con el correo del usuario */
    $cadena_desencriptada = desencriptar($cadena_encriptada_correcta);
    
    if (!$cadena_desencriptada) {
        // Si no se puede desencriptar, redirigir a la página de recuperación
        return $respon->withRedirect('/cambiar_password?msg_error=invalid_code');
    }

    include __DIR__ . '/../public/nuevo_password.php';
});

$app->post('/actualizar_usuario', function ($request, $response) {

    $new_password = filter_input(INPUT_POST, "nueva_password", FILTER_SANITIZE_STRING);
    $new_confirm_password = filter_input(INPUT_POST, "nueva_confirm_password", FILTER_SANITIZE_STRING);
    $mail = filter_input(INPUT_POST, "mail", FILTER_SANITIZE_STRING);
    include __DIR__ . '/../php/actualizar_usuario.php';
});

$app->post('/remove_photo_user', function ($request, $respon) {
    include __DIR__ . '/../php/remove_photo_user.php';
});

$app->post('/cambiar_foto_usuario', function ($request, $respon) {



    include __DIR__ . '/../php/cambiar_foto_usuario.php';
});

$app->get('/logout', function ($request, $respon) {
    include __DIR__ . '/../php/logout.php';
});

/* ------------------------- USUARIO EXTERNO ----------------------- */

//     $app->get('/mis_codigos', function($request, $respon){

//         $usuario = getObjectUser('_id', $_SESSION['user_id']);
//         $title = "Lista de códigos de " . $usuario["username"];
//         $description = "&#9989; Miles de códigos en " . $GLOBALS["author"];
//         if($_SESSION["user_id"]==== null || empty($_SESSION["user_id"])){
//             print "<script>alert(\"!Acceso no permitido! Por favor, inicia sesión para acceder a esta página.\");window.location='". $GLOBALS["website"] . "';</script>";
//         } else {
//             include __DIR__ . '/../public/mis_codigos.php';
//         }
//     });

/* ------------------------- INSERTAR ----------------------- */



/* ------------------------- AJAX ----------------------- */



$app->post('/list_elements_bd', function ($request, $respon) {
    include __DIR__ . '/../php/list_elements_bd.php';
});

//     $app->post('/combo_dependiente', function($request, $respon){
//         include __DIR__ . '/../php/combo_dependiente.php';
//     });

$app->post('/comprobar_existe_codigo', function ($request, $respon) {
    include __DIR__ . '/../php/comprobar_existe_codigo.php';
});

$app->post('/cargar_localidades', function ($request, $respon) {
    include __DIR__ . '/../php/cargar_localidades.php';
});






// API endpoints para el bot de Telegram
$app->group('/api_final', function () use ($app) {

    // Verificar número de teléfono
    $app->post('/verify', function ($request, $response) {
        debug_log('API /verify called');
        debug_log('Request headers:', getallheaders());
        debug_log('Request body:', file_get_contents('php://input'));

        try {
            $data = $request->getParsedBody();
            debug_log('Parsed request data:', $data);

            if (!$data) {
                debug_log('No data received in request');
                return $response->withJson([
                    'error' => 'No data received'
                ], 400);
            }

            $phone = $data['phone'] ?? '';
            debug_log('Phone number:', $phone);

            if (!$phone) {
                debug_log('Phone number missing');
                return $response->withJson([
                    'error' => 'Phone number is required'
                ], 400);
            }

            debug_log('Looking up user with phone:', $phone);
            $usuario = getObjectUser('telefono', $phone);
            debug_log('User lookup result:', $usuario);

            if ($usuario) {
                return $response->withJson([
                    'success' => true,
                    'user_id' => (string) $usuario['_id'],
                    'username' => $usuario['username']
                ]);
            }

            return $response->withJson([
                'error' => 'User not found'
            ], 404);

        } catch (Exception $e) {
            debug_log('Exception in /verify:', $e);
            return $response->withJson([
                'error' => 'Internal server error',
                'message' => $e->getMessage(),
                'file' => $e->getFile(),
                'line' => $e->getLine()
            ], 500);
        }
    });

    // Obtener códigos de un usuario
    $app->get('/codes', function ($request, $response) {
        $userId = $request->getHeaderLine('user_id');

        if (!$userId) {
            return $response->withJson([
                'error' => 'User ID is required'
            ], 400);
        }

        try {
            // Obtener códigos del usuario
            $array_filtro = [
                "id_usuario" => $userId,
                "estado" => array('$in' => [0, -1, 1])
            ];

            $array_opciones = [
                "limit" => 50,
                "sort" => ["_id" => -1]
            ];

            $codigos = get_all_listado_codigos_array($array_filtro, $array_opciones);

            // Formatear respuesta
            $formatted_codes = [];
            foreach ($codigos['results'] as $codigo) {
                $marca = getObjectMarca('nombre_clave', $codigo['marca']);

                $formatted_codes[] = [
                    'id' => (string) $codigo['_id'],
                    'game' => $marca['nombre'] ?? $codigo['marca'],
                    'code' => $codigo['codigo'],
                    'date' => date('Y-m-d', strtotime($codigo['fecha'])),
                    'description' => $codigo['descripcion'],
                    'status' => $codigo['estado']
                ];
            }

            return $response->withJson($formatted_codes);

        } catch (Exception $e) {
            return $response->withJson([
                'error' => 'Internal server error'
            ], 500);
        }
    });

    // Añadir nuevo código
    $app->post('/codes', function ($request, $response) {
        $data = $request->getParsedBody();
        $userId = $request->getHeaderLine('user_id');

        if (!$userId || !isset($data['marca']) || !isset($data['codigo'])) {
            return $response->withJson([
                'error' => 'Missing required fields'
            ], 400);
        }

        try {
            $newCode = [
                'marca' => $data['marca'],
                'codigo' => $data['codigo'],
                'descripcion' => $data['descripcion'] ?? '',
                'id_usuario' => $userId
            ];

            $result = addNewCode($newCode, $userId);

            if ($result) {
                return $response->withJson([
                    'success' => true,
                    'code_id' => (string) $result
                ]);
            }

            return $response->withJson([
                'error' => 'Failed to add code'
            ], 500);

        } catch (Exception $e) {
            return $response->withJson([
                'error' => 'Internal server error'
            ], 500);
        }
    });

    // Modificar código existente
    $app->put('/codes/{id}', function ($request, $response, $args) {
        $codeId = $args['id'];
        $userId = $request->getHeaderLine('user_id');
        $data = $request->getParsedBody();

        if (!$userId || !$codeId) {
            return $response->withJson([
                'error' => 'Missing required fields'
            ], 400);
        }

        try {
            // Verificar que el código pertenece al usuario
            $codigo = getCodeByID(new \MongoDB\BSON\ObjectId($codeId));

            if (!$codigo || $codigo['id_usuario'] !== $userId) {
                return $response->withJson([
                    'error' => 'Code not found or unauthorized'
                ], 404);
            }

            // Actualizar código
            $updateData = [
                'codigo_id' => $codeId,
                'codigo' => $data['codigo'] ?? $codigo['codigo'],
                'descripcion' => $data['descripcion'] ?? $codigo['descripcion'],
                'marca' => $data['marca'] ?? $codigo['marca']
            ];

            $result = updateExistingCode($updateData, $userId);

            if ($result) {
                return $response->withJson([
                    'success' => true
                ]);
            }

            return $response->withJson([
                'error' => 'Failed to update code'
            ], 500);

        } catch (Exception $e) {
            return $response->withJson([
                'error' => 'Internal server error'
            ], 500);
        }
    });

});






// Grupo de rutas para páginas de tendencias/guías
$app->group('/guias', function () use ($app) {
    
    // Ruta para exchanges que no informan a hacienda
    $app->get('/exchanges-que-no-informan-a-hacienda', function ($request, $respon) {
        return renderTrendPage($respon, [
            'template' => 'exchanges_hacienda',
            'title' => '¿Cuáles son los exchanges que no informan a Hacienda? Descúbrelos',
            'description' => 'Explora cuáles son los exchanges de criptomonedas que no informan a Hacienda, sus características y las implicaciones legales para los usuarios.',
            'imagen_social' => 'img/guias/exchanges-hacienda-social.jpg',
            'categoria' => 'crypto'
        ]);
    });
    
    // Ruta para neobancos que no informan a hacienda
    $app->get('/neobancos-que-no-informan-a-hacienda', function ($request, $respon) {
        return renderTrendPage($respon, [
            'template' => 'neobancos_hacienda',
            'title' => '¿Qué neobancos no informan a Hacienda? Lista completa',
            'description' => 'Descubre qué neobancos no informan automáticamente a Hacienda, sus ventajas y desventajas, y las consideraciones legales importantes.',
            'imagen_social' => 'img/guias/neobancos-hacienda-social.jpg',
            'categoria' => 'fintech'
        ]);
    });
    
    // Puedes seguir añadiendo más rutas para otras páginas de tendencias aquí
});

// Función helper para renderizar páginas de tendencias
function renderTrendPage($respon, $pageData) {
    global $author_web, $name_page;
    
    $title = $pageData['title'];
    $description = $pageData['description'] . ' - ' . $author_web;
    $imagen_social = 'https://www.codigoamigo.com/' . $pageData['imagen_social'];
    $categoria = $pageData['categoria'] ?? '';
    
    $name_page = $pageData['template'];
    include_once $_SERVER['DOCUMENT_ROOT'] . '/public/guias/' . $pageData['template'] . '.php';
    
    return $respon;
}

// Ejecutar el footer (ya se incluye a través de inc/includes.php)
get_footer();

// Ejecutar la aplicación Slim
$app->run();

