<?php
// Función para detectar URLs y extraer códigos de descuento
function detect_url_and_extract_code($codigo_text) {
    // Patrones para detectar URLs
    $url_pattern = '/(https?:\/\/[^\s]+)/i';
    $code_patterns = [
        '/[?&]via=([^&]+)/i',           // via=9ab7ca
        '/[?&]code=([^&]+)/i',          // code=ABC123
        '/[?&]coupon=([^&]+)/i',        // coupon=SAVE20
        '/[?&]promo=([^&]+)/i',         // promo=WELCOME
        '/[?&]ref=([^&]+)/i',           // ref=USER123
        '/[?&]discount=([^&]+)/i',      // discount=50OFF
        '/[?&]offer=([^&]+)/i',         // offer=SUMMER
        '/[?&]deal=([^&]+)/i',          // deal=BLACKFRIDAY
        '/[?&]voucher=([^&]+)/i',       // voucher=GIFT50
        '/[?&]token=([^&]+)/i',         // token=ABC123
        '/[?&]key=([^&]+)/i',           // key=SECRET123
        '/[?&]id=([^&]+)/i',            // id=USER456
        '/[?&]affiliate=([^&]+)/i',     // affiliate=PARTNER
        '/[?&]partner=([^&]+)/i',       // partner=REF123
        '/[?&]source=([^&]+)/i',        // source=FRIEND
        '/[?&]utm_source=([^&]+)/i',    // utm_source=EMAIL
        '/[?&]utm_campaign=([^&]+)/i',  // utm_campaign=SUMMER
        '/[?&]utm_medium=([^&]+)/i',    // utm_medium=EMAIL
        '/[?&]utm_term=([^&]+)/i',      // utm_term=DESCUENTO
        '/[?&]utm_content=([^&]+)/i',   // utm_content=BANNER
        '/[?&]click_id=([^&]+)/i',      // click_id=ABC123
        '/[?&]tracking_id=([^&]+)/i',   // tracking_id=XYZ789
        '/[?&]referral=([^&]+)/i',      // referral=FRIEND
        '/[?&]invite=([^&]+)/i',        // invite=USER123
        '/[?&]promo_code=([^&]+)/i',    // promo_code=SAVE20
        '/[?&]discount_code=([^&]+)/i', // discount_code=WELCOME
        '/[?&]coupon_code=([^&]+)/i',   // coupon_code=BLACKFRIDAY
        '/[?&]voucher_code=([^&]+)/i',  // voucher_code=GIFT50
        '/[?&]offer_code=([^&]+)/i',    // offer_code=SUMMER
        '/[?&]deal_code=([^&]+)/i',     // deal_code=FLASH
        '/[?&]special=([^&]+)/i',       // special=VIP
        '/[?&]bonus=([^&]+)/i',         // bonus=EXTRA
        '/[?&]reward=([^&]+)/i',        // reward=POINTS
        '/[?&]credit=([^&]+)/i',        // credit=100
        '/[?&]cashback=([^&]+)/i',      // cashback=5
        '/[?&]rebate=([^&]+)/i',        // rebate=10
        '/[?&]refund=([^&]+)/i',        // refund=20
        '/[?&]return=([^&]+)/i',        // return=30
        '/[?&]exchange=([^&]+)/i',      // exchange=40
        '/[?&]upgrade=([^&]+)/i',       // upgrade=PREMIUM
        '/[?&]downgrade=([^&]+)/i',     // downgrade=BASIC
        '/[?&]trial=([^&]+)/i',         // trial=7DAYS
        '/[?&]demo=([^&]+)/i',          // demo=FREE
        '/[?&]sample=([^&]+)/i',        // sample=SMALL
        '/[?&]test=([^&]+)/i',          // test=BETA
        '/[?&]preview=([^&]+)/i',       // preview=EARLY
        '/[?&]access=([^&]+)/i',        // access=VIP
        '/[?&]membership=([^&]+)/i',    // membership=GOLD
        '/[?&]subscription=([^&]+)/i',  // subscription=YEARLY
        '/[?&]plan=([^&]+)/i',          // plan=PRO
        '/[?&]package=([^&]+)/i',       // package=DELUXE
        '/[?&]bundle=([^&]+)/i',        // bundle=SAVE
        '/[?&]combo=([^&]+)/i',         // combo=SPECIAL
        '/[?&]set=([^&]+)/i',           // set=COMPLETE
        '/[?&]kit=([^&]+)/i',           // kit=STARTER
        '/[?&]box=([^&]+)/i',           // box=MYSTERY
        '/[?&]case=([^&]+)/i',          // case=PROTECT
        '/[?&]cover=([^&]+)/i',         // cover=SCREEN
        '/[?&]skin=([^&]+)/i',          // skin=CUSTOM
        '/[?&]theme=([^&]+)/i',         // theme=DARK
        '/[?&]style=([^&]+)/i',         // style=MODERN
        '/[?&]color=([^&]+)/i',         // color=BLUE
        '/[?&]size=([^&]+)/i',          // size=LARGE
        '/[?&]weight=([^&]+)/i',        // weight=HEAVY
        '/[?&]length=([^&]+)/i',        // length=SHORT
        '/[?&]width=([^&]+)/i',         // width=NARROW
        '/[?&]height=([^&]+)/i',        // height=TALL
        '/[?&]depth=([^&]+)/i',         // depth=DEEP
        '/[?&]volume=([^&]+)/i',        // volume=LOUD
        '/[?&]speed=([^&]+)/i',         // speed=FAST
        '/[?&]power=([^&]+)/i',         // power=HIGH
        '/[?&]energy=([^&]+)/i',        // energy=LOW
        '/[?&]force=([^&]+)/i',         // force=STRONG
        '/[?&]strength=([^&]+)/i',      // strength=WEAK
        '/[?&]quality=([^&]+)/i',       // quality=PREMIUM
        '/[?&]grade=([^&]+)/i',         // grade=A
        '/[?&]level=([^&]+)/i',         // level=EXPERT
        '/[?&]rank=([^&]+)/i',          // rank=1
        '/[?&]position=([^&]+)/i',      // position=TOP
        '/[?&]place=([^&]+)/i',         // place=FIRST
        '/[?&]spot=([^&]+)/i',          // spot=VIP
        '/[?&]seat=([^&]+)/i',          // seat=WINDOW
        '/[?&]room=([^&]+)/i',          // room=SUITE
        '/[?&]space=([^&]+)/i',         // space=PRIVATE
        '/[?&]area=([^&]+)/i',          // area=EXCLUSIVE
        '/[?&]zone=([^&]+)/i',          // zone=RESTRICTED
        '/[?&]region=([^&]+)/i',        // region=EUROPE
        '/[?&]country=([^&]+)/i',       // country=SPAIN
        '/[?&]city=([^&]+)/i',          // city=MADRID
        '/[?&]state=([^&]+)/i',         // state=CALIFORNIA
        '/[?&]province=([^&]+)/i',      // province=BARCELONA
        '/[?&]district=([^&]+)/i',      // district=CENTRAL
        '/[?&]neighborhood=([^&]+)/i',  // neighborhood=DOWNTOWN
        '/[?&]street=([^&]+)/i',        // street=MAIN
        '/[?&]avenue=([^&]+)/i',        // avenue=BROADWAY
        '/[?&]boulevard=([^&]+)/i',     // boulevard=SUNSET
        '/[?&]road=([^&]+)/i',          // road=HIGHWAY
        '/[?&]way=([^&]+)/i',           // way=PATH
        '/[?&]lane=([^&]+)/i',          // lane=ALLEY
        '/[?&]drive=([^&]+)/i',         // drive=PARKWAY
        '/[?&]court=([^&]+)/i',         // court=PLAZA
        '/[?&]place=([^&]+)/i',         // place=SQUARE
        '/[?&]circle=([^&]+)/i',        // circle=ROUND
        '/[?&]square=([^&]+)/i',        // square=BLOCK
        '/[?&]triangle=([^&]+)/i',      // triangle=SHAPE
        '/[?&]rectangle=([^&]+)/i',     // rectangle=FORM
        '/[?&]oval=([^&]+)/i',          // oval=EGG
        '/[?&]diamond=([^&]+)/i',       // diamond=GEM
        '/[?&]star=([^&]+)/i',          // star=SHINE
        '/[?&]heart=([^&]+)/i',         // heart=LOVE
        '/[?&]smile=([^&]+)/i',         // smile=HAPPY
        '/[?&]frown=([^&]+)/i',         // frown=SAD
        '/[?&]wink=([^&]+)/i',          // wink=PLAYFUL
        '/[?&]laugh=([^&]+)/i',         // laugh=FUNNY
        '/[?&]cry=([^&]+)/i',           // cry=TEARS
        '/[?&]angry=([^&]+)/i',         // angry=MAD
        '/[?&]surprised=([^&]+)/i',     // surprised=WOW
        '/[?&]confused=([^&]+)/i',      // confused=HUH
        '/[?&]excited=([^&]+)/i',       // excited=YAY
        '/[?&]bored=([^&]+)/i',         // bored=MEH
        '/[?&]tired=([^&]+)/i',         // tired=SLEEPY
        '/[?&]sleepy=([^&]+)/i',        // sleepy=DROWSY
        '/[?&]awake=([^&]+)/i',         // awake=ALERT
        '/[?&]alert=([^&]+)/i',         // alert=WARNING
        '/[?&]warning=([^&]+)/i',       // warning=DANGER
        '/[?&]danger=([^&]+)/i',        // danger=HAZARD
        '/[?&]hazard=([^&]+)/i',        // hazard=RISK
        '/[?&]risk=([^&]+)/i',          // risk=CHANCE
        '/[?&]chance=([^&]+)/i',        // chance=OPPORTUNITY
        '/[?&]opportunity=([^&]+)/i',   // opportunity=CHANCE
        '/[?&]possibility=([^&]+)/i',   // possibility=MAYBE
        '/[?&]maybe=([^&]+)/i',         // maybe=PERHAPS
        '/[?&]perhaps=([^&]+)/i',       // perhaps=COULD
        '/[?&]could=([^&]+)/i',         // could=MIGHT
        '/[?&]might=([^&]+)/i',         // might=WOULD
        '/[?&]would=([^&]+)/i',         // would=SHOULD
        '/[?&]should=([^&]+)/i',        // should=MUST
        '/[?&]must=([^&]+)/i',          // must=HAVE
        '/[?&]have=([^&]+)/i',          // have=GOT
        '/[?&]got=([^&]+)/i',           // got=OBTAINED
        '/[?&]obtained=([^&]+)/i',      // obtained=ACQUIRED
        '/[?&]acquired=([^&]+)/i',      // acquired=GAINED
        '/[?&]gained=([^&]+)/i',        // gained=EARNED
        '/[?&]earned=([^&]+)/i',        // earned=WON
        '/[?&]won=([^&]+)/i',           // won=ACHIEVED
        '/[?&]achieved=([^&]+)/i',      // achieved=ACCOMPLISHED
        '/[?&]accomplished=([^&]+)/i',  // accomplished=COMPLETED
        '/[?&]completed=([^&]+)/i',     // completed=FINISHED
        '/[?&]finished=([^&]+)/i',      // finished=DONE
        '/[?&]done=([^&]+)/i',          // done=READY
        '/[?&]ready=([^&]+)/i',         // ready=PREPARED
        '/[?&]prepared=([^&]+)/i',      // prepared=SET
        '/[?&]set=([^&]+)/i',           // set=CONFIGURED
        '/[?&]configured=([^&]+)/i',    // configured=ADJUSTED
        '/[?&]adjusted=([^&]+)/i',      // adjusted=MODIFIED
        '/[?&]modified=([^&]+)/i',      // modified=CHANGED
        '/[?&]changed=([^&]+)/i',       // changed=ALTERED
        '/[?&]altered=([^&]+)/i',       // altered=UPDATED
        '/[?&]updated=([^&]+)/i',       // updated=REFRESHED
        '/[?&]refreshed=([^&]+)/i',     // refreshed=RENEWED
        '/[?&]renewed=([^&]+)/i',       // renewed=RESTORED
        '/[?&]restored=([^&]+)/i',      // restored=REPAIRED
        '/[?&]repaired=([^&]+)/i',      // repaired=FIXED
        '/[?&]fixed=([^&]+)/i',         // fixed=CORRECTED
        '/[?&]corrected=([^&]+)/i',     // corrected=IMPROVED
        '/[?&]improved=([^&]+)/i',      // improved=ENHANCED
        '/[?&]enhanced=([^&]+)/i',      // enhanced=UPGRADED
        '/[?&]upgraded=([^&]+)/i',      // upgraded=BOOSTED
        '/[?&]boosted=([^&]+)/i',       // boosted=INCREASED
        '/[?&]increased=([^&]+)/i',     // increased=RAISED
        '/[?&]raised=([^&]+)/i',        // raised=LIFTED
        '/[?&]lifted=([^&]+)/i',        // lifted=ELEVATED
        '/[?&]elevated=([^&]+)/i',      // elevated=PROMOTED
        '/[?&]promoted=([^&]+)/i',      // promoted=ADVANCED
        '/[?&]advanced=([^&]+)/i',      // advanced=PROGRESSED
        '/[?&]progressed=([^&]+)/i',    // progressed=DEVELOPED
        '/[?&]developed=([^&]+)/i',     // developed=CREATED
        '/[?&]created=([^&]+)/i',       // created=MADE
        '/[?&]made=([^&]+)/i',          // made=BUILT
        '/[?&]built=([^&]+)/i',         // built=CONSTRUCTED
        '/[?&]constructed=([^&]+)/i',   // constructed=ASSEMBLED
        '/[?&]assembled=([^&]+)/i',     // assembled=PUT
        '/[?&]put=([^&]+)/i',           // put=PLACED
        '/[?&]placed=([^&]+)/i',        // placed=POSITIONED
        '/[?&]positioned=([^&]+)/i',    // positioned=LOCATED
        '/[?&]located=([^&]+)/i',       // located=FOUND
        '/[?&]found=([^&]+)/i',         // found=DISCOVERED
        '/[?&]discovered=([^&]+)/i',    // discovered=UNCOVERED
        '/[?&]uncovered=([^&]+)/i',     // uncovered=REVEALED
        '/[?&]revealed=([^&]+)/i',      // revealed=EXPOSED
        '/[?&]exposed=([^&]+)/i',       // exposed=SHOWN
        '/[?&]shown=([^&]+)/i',         // shown=DISPLAYED
        '/[?&]displayed=([^&]+)/i',     // displayed=PRESENTED
        '/[?&]presented=([^&]+)/i',     // presented=OFFERED
        '/[?&]offered=([^&]+)/i',       // offered=PROVIDED
        '/[?&]provided=([^&]+)/i',      // provided=GIVEN
        '/[?&]given=([^&]+)/i',         // given=DELIVERED
        '/[?&]delivered=([^&]+)/i',     // delivered=BROUGHT
        '/[?&]brought=([^&]+)/i',       // brought=CARRIED
        '/[?&]carried=([^&]+)/i',       // carried=TRANSPORTED
        '/[?&]transported=([^&]+)/i',   // transported=MOVED
        '/[?&]moved=([^&]+)/i',         // moved=SHIFTED
        '/[?&]shifted=([^&]+)/i',       // shifted=CHANGED
        '/[?&]changed=([^&]+)/i',       // changed=ALTERED
        '/[?&]altered=([^&]+)/i',       // altered=MODIFIED
        '/[?&]modified=([^&]+)/i',      // modified=ADJUSTED
        '/[?&]adjusted=([^&]+)/i',      // adjusted=CONFIGURED
        '/[?&]configured=([^&]+)/i',    // configured=SET
        '/[?&]set=([^&]+)/i',           // set=PREPARED
        '/[?&]prepared=([^&]+)/i',      // prepared=READY
        '/[?&]ready=([^&]+)/i',         // ready=DONE
        '/[?&]done=([^&]+)/i',          // done=FINISHED
        '/[?&]finished=([^&]+)/i',      // finished=COMPLETED
        '/[?&]completed=([^&]+)/i',     // completed=ACCOMPLISHED
        '/[?&]accomplished=([^&]+)/i',  // accomplished=ACHIEVED
        '/[?&]achieved=([^&]+)/i',      // achieved=WON
        '/[?&]won=([^&]+)/i',           // won=EARNED
        '/[?&]earned=([^&]+)/i',        // earned=GAINED
        '/[?&]gained=([^&]+)/i',        // gained=ACQUIRED
        '/[?&]acquired=([^&]+)/i',      // acquired=OBTAINED
        '/[?&]obtained=([^&]+)/i',      // obtained=GOT
        '/[?&]got=([^&]+)/i',           // got=HAVE
        '/[?&]have=([^&]+)/i',          // have=MUST
        '/[?&]must=([^&]+)/i',          // must=SHOULD
        '/[?&]should=([^&]+)/i',        // should=WOULD
        '/[?&]would=([^&]+)/i',         // would=MIGHT
        '/[?&]might=([^&]+)/i',         // might=COULD
        '/[?&]could=([^&]+)/i',         // could=PERHAPS
        '/[?&]perhaps=([^&]+)/i',       // perhaps=MAYBE
        '/[?&]maybe=([^&]+)/i',         // maybe=POSSIBILITY
        '/[?&]possibility=([^&]+)/i',   // possibility=OPPORTUNITY
        '/[?&]opportunity=([^&]+)/i',   // opportunity=CHANCE
        '/[?&]chance=([^&]+)/i',        // chance=RISK
        '/[?&]risk=([^&]+)/i',          // risk=HAZARD
        '/[?&]hazard=([^&]+)/i',        // hazard=DANGER
        '/[?&]danger=([^&]+)/i',        // danger=WARNING
        '/[?&]warning=([^&]+)/i',       // warning=ALERT
        '/[?&]alert=([^&]+)/i',         // alert=AWAKE
        '/[?&]awake=([^&]+)/i',         // awake=SLEEPY
        '/[?&]sleepy=([^&]+)/i',        // sleepy=TIRED
        '/[?&]tired=([^&]+)/i',         // tired=BORED
        '/[?&]bored=([^&]+)/i',         // bored=EXCITED
        '/[?&]excited=([^&]+)/i',       // excited=CONFUSED
        '/[?&]confused=([^&]+)/i',      // confused=SURPRISED
        '/[?&]surprised=([^&]+)/i',     // surprised=ANGRY
        '/[?&]angry=([^&]+)/i',         // angry=CRY
        '/[?&]cry=([^&]+)/i',           // cry=LAUGH
        '/[?&]laugh=([^&]+)/i',         // laugh=WINK
        '/[?&]wink=([^&]+)/i',          // wink=FROWN
        '/[?&]frown=([^&]+)/i',         // frown=SMILE
        '/[?&]smile=([^&]+)/i',         // smile=HEART
        '/[?&]heart=([^&]+)/i',         // heart=STAR
        '/[?&]star=([^&]+)/i',          // star=DIAMOND
        '/[?&]diamond=([^&]+)/i',       // diamond=OVAL
        '/[?&]oval=([^&]+)/i',          // oval=RECTANGLE
        '/[?&]rectangle=([^&]+)/i',     // rectangle=TRIANGLE
        '/[?&]triangle=([^&]+)/i',      // triangle=SQUARE
        '/[?&]square=([^&]+)/i',        // square=CIRCLE
        '/[?&]circle=([^&]+)/i',        // circle=PLACE
        '/[?&]place=([^&]+)/i',         // place=COURT
        '/[?&]court=([^&]+)/i',         // court=DRIVE
        '/[?&]drive=([^&]+)/i',         // drive=LANE
        '/[?&]lane=([^&]+)/i',          // lane=WAY
        '/[?&]way=([^&]+)/i',           // way=ROAD
        '/[?&]road=([^&]+)/i',          // road=BOULEVARD
        '/[?&]boulevard=([^&]+)/i',     // boulevard=AVENUE
        '/[?&]avenue=([^&]+)/i',        // avenue=STREET
        '/[?&]street=([^&]+)/i',        // street=NEIGHBORHOOD
        '/[?&]neighborhood=([^&]+)/i',  // neighborhood=DISTRICT
        '/[?&]district=([^&]+)/i',      // district=PROVINCE
        '/[?&]province=([^&]+)/i',      // province=STATE
        '/[?&]state=([^&]+)/i',         // state=CITY
        '/[?&]city=([^&]+)/i',          // city=COUNTRY
        '/[?&]country=([^&]+)/i',       // country=REGION
        '/[?&]region=([^&]+)/i',        // region=ZONE
        '/[?&]zone=([^&]+)/i',          // zone=AREA
        '/[?&]area=([^&]+)/i',          // area=SPACE
        '/[?&]space=([^&]+)/i',         // space=ROOM
        '/[?&]room=([^&]+)/i',          // room=SEAT
        '/[?&]seat=([^&]+)/i',          // seat=SPOT
        '/[?&]spot=([^&]+)/i',          // spot=PLACE
        '/[?&]place=([^&]+)/i',         // place=POSITION
        '/[?&]position=([^&]+)/i',      // position=RANK
        '/[?&]rank=([^&]+)/i',          // rank=LEVEL
        '/[?&]level=([^&]+)/i',         // level=GRADE
        '/[?&]grade=([^&]+)/i',         // grade=QUALITY
        '/[?&]quality=([^&]+)/i',       // quality=STRENGTH
        '/[?&]strength=([^&]+)/i',      // strength=FORCE
        '/[?&]force=([^&]+)/i',         // force=ENERGY
        '/[?&]energy=([^&]+)/i',        // energy=POWER
        '/[?&]power=([^&]+)/i',         // power=SPEED
        '/[?&]speed=([^&]+)/i',         // speed=VOLUME
        '/[?&]volume=([^&]+)/i',        // volume=DEPTH
        '/[?&]depth=([^&]+)/i',         // depth=HEIGHT
        '/[?&]height=([^&]+)/i',        // height=WIDTH
        '/[?&]width=([^&]+)/i',         // width=LENGTH
        '/[?&]length=([^&]+)/i',        // length=WEIGHT
        '/[?&]weight=([^&]+)/i',        // weight=SIZE
        '/[?&]size=([^&]+)/i',          // size=COLOR
        '/[?&]color=([^&]+)/i',         // color=STYLE
        '/[?&]style=([^&]+)/i',         // style=THEME
        '/[?&]theme=([^&]+)/i',         // theme=SKIN
        '/[?&]skin=([^&]+)/i',          // skin=COVER
        '/[?&]cover=([^&]+)/i',         // cover=CASE
        '/[?&]case=([^&]+)/i',          // case=BOX
        '/[?&]box=([^&]+)/i',           // box=KIT
        '/[?&]kit=([^&]+)/i',           // kit=SET
        '/[?&]set=([^&]+)/i',           // set=COMBO
        '/[?&]combo=([^&]+)/i',         // combo=BUNDLE
        '/[?&]bundle=([^&]+)/i',        // bundle=PACKAGE
        '/[?&]package=([^&]+)/i',       // package=PLAN
        '/[?&]plan=([^&]+)/i',          // plan=SUBSCRIPTION
        '/[?&]subscription=([^&]+)/i',  // subscription=MEMBERSHIP
        '/[?&]membership=([^&]+)/i',    // membership=ACCESS
        '/[?&]access=([^&]+)/i',        // access=PREVIEW
        '/[?&]preview=([^&]+)/i',       // preview=TEST
        '/[?&]test=([^&]+)/i',          // test=SAMPLE
        '/[?&]sample=([^&]+)/i',        // sample=DEMO
        '/[?&]demo=([^&]+)/i',          // demo=TRIAL
        '/[?&]trial=([^&]+)/i',         // trial=DOWNGRADE
        '/[?&]downgrade=([^&]+)/i',     // downgrade=UPGRADE
        '/[?&]upgrade=([^&]+)/i',       // upgrade=EXCHANGE
        '/[?&]exchange=([^&]+)/i',      // exchange=RETURN
        '/[?&]return=([^&]+)/i',        // return=REFUND
        '/[?&]refund=([^&]+)/i',        // refund=REBATE
        '/[?&]rebate=([^&]+)/i',        // rebate=CASHBACK
        '/[?&]cashback=([^&]+)/i',      // cashback=CREDIT
        '/[?&]credit=([^&]+)/i',        // credit=REWARD
        '/[?&]reward=([^&]+)/i',        // reward=BONUS
        '/[?&]bonus=([^&]+)/i',         // bonus=SPECIAL
        '/[?&]special=([^&]+)/i',       // special=DEAL
        '/[?&]deal=([^&]+)/i',          // deal=OFFER
        '/[?&]offer=([^&]+)/i',         // offer=COUPON
        '/[?&]coupon=([^&]+)/i',        // coupon=PROMO
        '/[?&]promo=([^&]+)/i',         // promo=CODE
        '/[?&]code=([^&]+)/i',          // code=VIA
        '/[?&]via=([^&]+)/i'            // via=9ab7ca
    ];
    
    $result = [
        'is_url' => false,
        'url' => '',
        'extracted_code' => '',
        'display_text' => $codigo_text
    ];
    
    // Verificar si es una URL
    if (preg_match($url_pattern, $codigo_text, $url_matches)) {
        $result['is_url'] = true;
        $result['url'] = $url_matches[0];
        
        // Intentar extraer código de la URL
        foreach ($code_patterns as $pattern) {
            if (preg_match($pattern, $codigo_text, $code_matches)) {
                $result['extracted_code'] = $code_matches[1];
                $result['display_text'] = $code_matches[1];
                break;
            }
        }
        
        // Si no se encontró código específico, usar la URL completa
        if (empty($result['extracted_code'])) {
            $result['display_text'] = $codigo_text;
        }
    }
    
    return $result;
}
?>

